### ISSUE TITLE
Swagger Tanstack Query Example not working

### ISSUE THREAD

**Issue by KoolieKangarooMjolner** [kubb-labs/kubb#1003]
### What is the type of issue?

Example code is not working

### What is the issue?

The example config on the bottom of page https://kubb.dev/plugins/swagger-tanstack-query/ is not working.

Getting: **Error This plugin has a pre set that is not valid(["plugin-oas", "plugin-ts", "plugin-zod"]) [...]**

Also some of the plugins used in the example are missing from the installation example in the top of the page. 

Steps to reproduce:
``` 
pnpm create vite@latest [react + SWC Typescript]
cd [chosen-projectname]
pnpm install
pnpm add @tanstack/react-query
pnpm add @kubb/cli @kubb/core
pnpm add @kubb/swagger-tanstack-query @kubb/swagger-ts @kubb/swagger @kubb/swagger-client
pnpm add @kubb/plugin-oas // missing from above
// add script to package.json e.g. "codegen": "kubb --config ./kubb.config.ts"
// pnpm run codegen
```

### Where did you find it?

https://kubb.dev/plugins/swagger-tanstack-query/

**Comment by stijnvanhulle** [comment]
`@kubb/swagger` is deprecated in favour of `@kubb/plugin-oas`. So normally if you install that one it will work(I will update the docs).
If you are still using `@kubb/swagger` then your kubb.config.ts file will look like this:
```
import { defineConfig } from '@kubb/core'
import { definePlugin } from '@kubb/swagger'
import { pluginTs } from '@kubb/swagger-ts'

export default defineConfig(async () => {
  return {
    root: '.',
    input: {
      path: './petStore.yaml',
    },
    output: {
      path: './src/gen',
      clean: true,
    },
    plugins: [
      definePlugin(),
      pluginTs(),
    ],
  }
})
```

**Comment by KoolieKangarooMjolner** [comment]
Thank you. I am in the project startup process, so I am basically looking for something to create ts types/schemas and especially react-query hooks. The error I got though seemed to be linked to the swagger-tanstack-query plugin. Tried a clean project with setup as described above (pnpm create vite@latest etc.) and a config like this:
```
import { defineConfig } from '@kubb/core'
import { pluginOas } from '@kubb/plugin-oas'
import { pluginTanstackQuery } from '@kubb/swagger-tanstack-query'

export default defineConfig({
  input: {
    path: "https://petstore3.swagger.io/api/v3/openapi.json",//'./swagger.json',
  },
  output: {
    path: './src/gen',
  },
  plugins: [
    pluginOas(),
    pluginTanstackQuery({
      output: {
        path: './hooks',
      },
    }),
  ],
})
```

Commenting out the pluginTanstackQuery will make it work though. 

attached my package.json: 
[package.json](https://github.com/kubb-labs/kubb/files/15304099/package.json)

I will be happy to help out with docs if you need it, but need to get to know the framework to do that of course :)

**Comment by stijnvanhulle** [comment]
@kubb/swagger-tanstack-query needs `@kubb/swagger-ts`, can you try with adding the following:
I also did an update for the docs so normally it should now be correct.

```
import { defineConfig } from '@kubb/core'
import { pluginOas } from '@kubb/plugin-oas'
import { pluginTanstackQuery } from '@kubb/swagger-tanstack-query'
import { pluginTs } from '@kubb/swagger-ts'

export default defineConfig({
  input: {
    path: "https://petstore3.swagger.io/api/v3/openapi.json",//'./swagger.json',
  },
  output: {
    path: './src/gen',
  },
  plugins: [
    pluginOas(),
    pluginTs(),
    pluginTanstackQuery({
      output: {
        path: './hooks',
      },
    }),
  ],
})
```

**Comment by KoolieKangarooMjolner** [comment]
That did the job! Thank you!
