### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by csaba-veezla** [kubb-labs/kubb#1008]
### What version of `kubb` is running?

kubb/2.18.8 darwin-arm64 node-v22.2.0

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

Try to run kubb from the directory where the `kubb.config.ts` lies and try to repeat it from the parent directory.

Currently, kubb handles the relative paths in the config depending on the "working directory".
So starting kubb from a different directory can lead to errors or to different results.

### How often does this bug happen?

Every time

### What is the expected behavior?

I would expect, that the config would use the directory of `kubb.config.ts` as the point of reference when it comes to paths.

Like in the attached config file, I would expect, that the swagger file will be next to the kubb file, and kubb will look for it next to it, no matter in which directory I start kubb from.

### Additional information

```ts
import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginTs } from '@kubb/swagger-ts';
import { pluginTanstackQuery } from '@kubb/swagger-tanstack-query';
import { pluginZod } from '@kubb/swagger-zod';

export default defineConfig(async () => {
  return {
    root: '.',
    input: {
      path: './swagger.yaml',
    },
    output: {
      path: './src',
    },
    plugins: [
      pluginOas({ output: false }),
    ],
  };
});
```

**Comment by csaba-veezla** [comment]
Image for representation:
<img width="1401" alt="Screenshot 2024-05-21 at 14 30 38" src="https://github.com/kubb-labs/kubb/assets/169660185/9e27b30d-b0bd-4083-a282-b5adcaf654ef">

**Comment by stijnvanhulle** [comment]
@csaba-veezla This should be resolved in the latest version of Kubb.
