### ISSUE TITLE
pnpm exact version in package.json breaks install

### ISSUE THREAD

**Issue by kopach** [kubb-labs/kubb#1009]
### What version of `kubb` is running?

kubb@2.18.8

### What steps can reproduce the bug?

I'm trying to update `kubb` from `2.6.7 -> 2.18.8` and `pnpm` install fails due to incompatible with `kubb`

here is a portion of the PNPM log

```log
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

This error happened while installing a direct dependency of /tmp/renovate/repos/github/SmartBear/sap-web-client

Your pnpm version is incompatible with "registry.npmjs.org/@kubb/swagger-zod/2.18.8".

Expected version: >=8.15.0
Got: 8.6.12
```

while it's fine to keep exact package version in package.json for dev purposes, it should not go into delivered package within `package.json` unless it really won't work as package has dependency on `pnpm` itself (which I don't believe a case here)

---

Note, if I would use any other package manager - there won't be an issue with this.

### How often does this bug happen?

None

### What is the expected behavior?

please, remove `pnpm` from engines from "delivered" package.json (the one published to npm registry)

### Additional information

my `.npmrc` config
```.npmrc
engine-strict=true
strict-peer-dependencies=true
```

**Comment by stijnvanhulle** [comment]
@kopach To be honest, I was not aware of how strict PNPM was with those versions(even if they are not the main project). I will adapt so your issue can be resolved.

**Comment by stijnvanhulle** [comment]
@kopach  This should be resolved in the latest version of Kubb.

**Comment by kopach** [comment]
@stijnvanhulle thank you
