### ISSUE TITLE
Please extend zod generator with TS types from zod itself

### ISSUE THREAD

**Issue by kopach** [kubb-labs/kubb#1011]
### What is the problem this feature would solve?

Types generated from OpenAPI schema by TypeScript generator are far less strict than one provided by ZOD.
Would be really great if we could use TS types provided by ZOD itself since we do use zod parsing anyway

### External documents/projects?

docs reference below

https://zod.dev/?id=type-inference

> You can extract the TypeScript type of any schema with `z.infer<typeof mySchema>`
> ```ts
> const A = z.string();
> type A = z.infer<typeof A>; // string
> 
> const u: A = 12; // TypeError
> const u: A = "asdf"; // compiles
> ```

### What is the feature you are proposing to solve the problem?

add option (enabled by default) to `pluginZod` which would add `z.infer<typeof mySchema>`  to every zod schema generated by kubb (right in the same file as schema)

### What alternatives have you considered?

As workaround I do add those types using hooks like so

```js
  hooks: {
    done: [
      'replace-in-file --configFile=replace.config.cjs', // this should go as first hook otherwise won't work
      'prettier --loglevel silent generatedTypes/ --write', // we can apply code fomratting after
    ],
  },
  ```

and content of `replace.config.cjs` (this is config file for https://www.npmjs.com/package/replace-in-file)
```js
module.exports = {
  files: 'generatedTypes/zod/*.ts',
  from: /(export const (\w+) .*)$/gm, // this will find every line starting with export
  to: '$1\nexport type $2=z.infer<typeof $2>', // this will add one more line after one with export wrapping everything after export with z.infer
};
```

It works quite well for me so far and I really don't see any downside of having this natively handled by kubb

**Comment by csaba-veezla** [comment]
I feel, that the ts plugin should not change.
The zod plugin should be able to export types as well, by providing a type output path.
And plugins that have a dependency on the ts plugin, shouldn't or more like they should require zod(with ts path) or ts.

**Comment by Wykks** [comment]
Hello!

Very useful project, thanks a lot @stijnvanhulle!

I have the same concern about zod, it would be better to be able to export types with zod as well, this way we don't have the extras types when using zod

**Comment by stijnvanhulle** [comment]
So if I'm following, you guys want to export all types of the generated Zod schemas(based on z.infer)?

Something like this?
```
export const petSchema = z.object({ firstName: z.string() })
export type PetSchema = z.infer<typeof petSchema>

```

**Comment by stijnvanhulle** [comment]
In the next release of Kubb you can make the Zod plugin return the schema with the option 'typedSchema', see https://1065.docs.kubb.dev/plugins/swagger-zod/#typedschema.

See https://github.com/kubb-labs/kubb/pull/1065 for examples.
