### ISSUE TITLE
Add the ability to use the `coerce` option for primitives in the Zod plugin configuration.

### ISSUE THREAD

**Issue by vlanemcev** [kubb-labs/kubb#1028]
### What is the problem this feature would solve?

Very often there is a situation where the backend indicates the field type in the swagger scheme as  `number` - in fact we receive in the real response from the backend the type of the `string` within which our number is specified.

For example I have this schema in my swagger: 

<img width="287" alt="image" src="https://github.com/kubb-labs/kubb/assets/26767564/da20924e-f3cc-4a0d-a5d4-a1a52a29a0aa">

I use this Kubb config for Zod plugin: 

```
import { PluginZod } from "@kubb/swagger-zod";

type SharedZodPluginOptionsParams = {
  exportAsPrefix?: string;
  includeTagSuffix?: boolean;
};

// Define shared configuration for the Zod plugin
// https://www.kubb.dev/plugins/swagger-zod/
export const getSharedZodPluginOptions = ({
  exportAsPrefix = "",
  includeTagSuffix = true,
}: SharedZodPluginOptionsParams): PluginZod["options"] => ({
  output: {
    path: "./validationSchemas",
    exportAs: `${
      exportAsPrefix ? exportAsPrefix + "A" : "a"
    }piValidationSchemas`,
  },
  group: {
    type: "tag",
    output: `./validationSchemas/{{tag}}${
      includeTagSuffix ? "Controller" : ""
    }`,
    exportAs: "{{tag}}",
  },
  unknownType: "unknown",
  dateType: false,
  typed: true,
});
```

And as the output for this schema the Kubb generated this Zod schema: 

```
export const assetMarketStatsSchema = z.object({
  symbol: z.string().optional(),
  price: z.number().optional(),
  priceChange24h: z.number().optional(),
  priceChange24hPerc: z.number().optional(),
  volume24h: z.number().optional(),
  quoteVolume24h: z.number().optional(),
  circulatingSupply: z.number().optional(),
  marketCapitalisation: z.number().optional(),
  marketCapRank: z.number().optional(),
}) as z.ZodType<AssetMarketStats>;
```

But in fact, my backend response me with following body: 

```
{
      "symbol": "Some symbol",
      "price": "1234.1234",
      "priceChange24h": "1234.1234",
      "priceChange24hPerc": "1234.1234",
      "volume24h": "1234.1234",
      "quoteVolume24h": "1234.1234",
      "circulatingSupply": "123",
      "marketCapitalisation": "1234.1234",
      "marketCapRank": 1 
}
```

In that case my schema validation will fail, because schema expects number values. 

### External documents/projects?

https://zod.dev/?id=coercion-for-primitives

### What is the feature you are proposing to solve the problem?

I suggest implementing a `coerce` parameter for primitive value types. Thus, we could override / set the default in the generation configuration that we would like certain types to be cast / transformed to the values ​​​​we need.

In that case, after generation I will have following schema: 

```
z.object({
  symbol: z.string().optional(),
  price: z.coerce.number().optional(),
  priceChange24h: z.coerce.number().optional(),
  priceChange24hPerc: z.coerce.number().optional(),
  volume24h: z.coerce.number().optional(),
  quoteVolume24h: z.coerce.number().optional(),
  circulatingSupply: z.coerce.number().optional(),
  marketCapitalisation: z.coerce.number().optional(),
  marketCapRank: z.number().optional(),
});
```

And in case if the value to validation will be "the number inside string" - this validation will understand in correctly and give me number value as a result of validation. 

[Link to the playground with described solution](https://zod-playground.vercel.app?appdata=N4IgzgxgFgpgtgQxALhALwHQHsBGArGCAFwApgAdAOwAJqwBPOHLAG2WszCICcBLSgOYkAlNgAORXlkoIWIgDRVaYvhBjtMELDG5qMlAK5MdI8ZOmyFS6it5qAwlASCYAJgAsUDRi069h425TLAkpGTlhRRobVRhHZwE3TwAFP29fXRh9IxwTURDzcKtogDdWIySvDh9tTOzA4NCLCKjaAEcDLCIYADVyuEr02v8cvLMwy0jrCF5dAxYESUEAZQMxMRZ6Ib8sgNyg-KaiqejEbgBrGCJ7BDFeIlleMEWw7bq9sYKJluszy%2BvbgAlZznbwfA7jZrFAC%2BwgA3CB5CASrIDDAwCgANogCjRWxqdjkEAARlcAGZ3BhSRSiVFoVQQABdJElHRgMIoEBkjDkjAADhA0KAA)

### What alternatives have you considered?

I know that we can create custom template / mappers that will manage such things, but I think it's common feature-request, so it would be better to have it as part of configuration.

**Comment by vlanemcev** [comment]
Thank you sooo much!

**Comment by rafaelmardojai** [comment]
Sorry, how do I disable this?

**Comment by vlanemcev** [comment]
@rafaelmardojai As I understand - this functionality is using by default now.

@stijnvanhulle maybe we have a possibility to add it as configuration option instead?

**Comment by rafaelmardojai** [comment]
Right, in my use case I use Zod schemas with forms, and the `coerce` will cause my forms to have the literal string `undefined` when a form is in its "empty" state.

Also I guess `coerce` can be undesired in other scenarios and that's why it's not not the default behavior of Zod.

**Comment by stijnvanhulle** [comment]
There will be a new option called `coercion` that you can enable that will use `z.coerce.string()` instead of `z.string()`. I moved this to by default false and overridable with an option in the ZodPlugin.

See https://1051.docs.kubb.dev/plugins/swagger-zod/#coercion.

**Comment by rafaelmardojai** [comment]
Thanks a lot! Really appreciated.
