### ISSUE TITLE
[Bug] zod circular dependency

### ISSUE THREAD

**Issue by csaba-veezla** [kubb-labs/kubb#1029]
### What version of `kubb` is running?

2.19.5

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

We have a circular dependency in our schema, like Category can have a children with Category array.
I think, this is a fairly common scenario or at least something that should be handled properly.
The typescript infer fails on this, resulting in a build fail caused by the implicit any.
Here is how it should be handled:
https://zod.dev/?id=recursive-types
currently this is the generated code:
```ts
export const ctegorySchema = z.object({ 'id': z.string(), 'label': z.string(), 'children': z.array(z.lazy(() => categorySchema)).nullable().nullish() });
```
This might have some effect on #1011 as well.

### How often does this bug happen?

Every time

### What is the expected behavior?

The generated code should be:
```ts
export const ctegorySchema: z.ZodSchema<Category> = z.object({ 'id': z.string(), 'label': z.string(), 'children': z.array(z.lazy(() => categorySchema)).nullable().nullish() });
``` 
Where the type in z.ZodSchema is the one that the ts plugin generates.

**Comment by stijnvanhulle** [comment]
@csaba-veezla Would https://www.kubb.dev/plugins/swagger-zod/#typed help you out?
Example Code
```
import { z } from 'zod'
import type { Tag } from '../ts/Tag'

export const tagSchema = z.object({ id: z.coerce.number().optional(), name: z.coerce.string().optional() }) as z.ZodType<Tag>

```

**Comment by csaba-veezla** [comment]
@stijnvanhulle 
I missed that option, thanks, given the example, I guess it will.
I'll check and get back to you
