### ISSUE TITLE
Website is dead

### ISSUE THREAD

**Issue by Nick-Lucas** [kubb-labs/kubb#1040]
### What version of `kubb` is running?

-

### What platform is your computer?

-

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

-

### What steps can reproduce the bug?

https://kubb.dev/ - 404

![image](https://github.com/kubb-labs/kubb/assets/8896153/9faf4aa4-abd2-44f9-b8b0-e9693137a6af)

### How often does this bug happen?

None

### What is the expected behavior?

website not dead

**Comment by stijnvanhulle** [comment]
@Nick-Lucas The website should be up again :)
