### ISSUE TITLE
Imports not taking into consideration models transformation name

### ISSUE THREAD

**Issue by vitorcamachoo** [kubb-labs/kubb#1042]
### What version of `kubb` is running?

2.19.6

### What platform is your computer?

MacOs

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"@kubb/cli": "^2.19.6",     "@kubb/core": "^2.19.6",  "@kubb/plugin-oas": "2.19.6",     "@kubb/swagger": "2.19.6",     "@kubb/swagger-client": "2.19.6",     "@kubb/swagger-tanstack-query": "2.19.6",     "@kubb/swagger-ts": "2.19.6",

### What steps can reproduce the bug?

// Kubb config
```ts
const transformers = {
    name(name: string, type?: "function" | "type" | "file" | undefined) {
        if (type === 'file') return `${name[0].toLowerCase() + name.slice(1)}`;
        return name;
    },
};

export default defineConfig({
    root: '.',
    input: { path: './api/schema.yaml' },
    output: {
        path: './src/api',
        clean: true,
    },
    plugins: [
        pluginOas({ output: false }),
        pluginTs({
            output: { path: './model' },
            enumType: 'asConst',
            transformers,
        }),
        pluginClient({
            client: { importPath: '../../axios/custom-instance' },
            output: { path: './api/index.ts' },
        }),
    ],
});
```
Based on this configuration, I was expecting that the `@kubb/swagger-client` would be aware of the name transformation. What is happening is that when importing the model types, the suffix "Schema" is not being added to the import:
![Screenshot 2024-06-18 at 11 50 25](https://github.com/kubb-labs/kubb/assets/20595956/428d80ac-c5aa-4ee1-8132-6a4c777b8f09)

![Screenshot 2024-06-18 at 11 50 38](https://github.com/kubb-labs/kubb/assets/20595956/22849f50-20d3-4912-a6f9-878255cf683c)

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
Will be fixed as part of https://github.com/kubb-labs/kubb/issues/1031
