### ISSUE TITLE
Cannot change param name from 'page' to 'cursor'.  getNextPageParam: (lastPage) => lastPage["cursor"], returns the cursor as page="cursorValue"

### ISSUE THREAD

**Issue by gentrith44belt** [kubb-labs/kubb#1053]
### What version of `kubb` is running?
v2.19.5

### What platform is your computer?
MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)
5

### What steps can reproduce the bug?
Basically the issue is that I cannot change {page: pageParam}  to be something like {cursor: ''}, whatever getNextPageParam returns it is appended to page

![image](https://github.com/kubb-labs/kubb/assets/143590367/334afea6-31a9-4c9e-8c0e-46a9887b0f82)
![image](https://github.com/kubb-labs/kubb/assets/143590367/111c8346-ffce-4b80-ab25-bfd2a8383c4c)

```typescript
	const getProjectsQuery = useGetProjectsInfinite(
		{
			filter: debouncedFilter.trim(),
		},
		{
			query: {
				initialPageParam: 0,
				getNextPageParam: (lastPage) => {
					return lastPage.data?.cursor;
				},
			},
		}
	);
```

**Comment by gentrith44belt** [comment]
`export function getProjectsInfiniteQueryOptions(
	params?: GetProjects["queryParams"],
	options: GetProjects["client"]["parameters"] = {}
) {
	const queryKey = getProjectsInfiniteQueryKey(params);
	return infiniteQueryOptions({
		queryKey,
		queryFn: async ({ pageParam }) => {
			const res = await client<GetProjects["data"], GetProjects["error"]>({
				method: "get",
				url: `/api/v1/customer/projects`,
				...options,
				params: {
					...params,
					["page"]: pageParam,
					...(options.params || {}),
				},
			});
			return res.data;
		},
		initialPageParam: 0,
		getNextPageParam: (lastPage) => lastPage["cursor"],
		getPreviousPageParam: (firstPage) => firstPage["cursor"],
	});
}`

**Comment by stijnvanhulle** [comment]
Setting `infinite.queryParam` to 'cursor' does not work in the `kubb.config.js`?

**Comment by gentrith44belt** [comment]
@stijnvanhulle 
Actually it does, but is that supposed to be used for page based pagination?
We use two strategies for infinite loading, cursor based and page based, so seems that it is not possible to generate different query param names for different strategies?

**Comment by stijnvanhulle** [comment]
@gentrith44belt I would suggest using https://www.kubb.dev/plugins/swagger-tanstack-query/#override and defining based on path/operation what your `queryParam` and `cursorparam` will be. 
With Kubb we can not know what the cursor is and what is paginated so that's why both options are there and it's then up to the implementer to define which one to be used.

**Comment by gentrith44belt** [comment]
@stijnvanhulle I will take a look, we changed the backend to use the same parameter name. Thanks for the response, keep up the good work 👍
