### ISSUE TITLE
FormData Typescript error when autogenerating react-query mutations

### ISSUE THREAD

**Issue by gentrith44belt** [kubb-labs/kubb#1064]
### What version of `kubb` is running?

2.21.0

### What platform is your computer?

macOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

5.48.0

### What steps can reproduce the bug?

Maybe there is a way to bypass this, but it breaks builds and I didn't see a way to override it from the kubb config.
The commented code is one of the solutions.

![image](https://github.com/kubb-labs/kubb/assets/143590367/286b45df-8dea-44d8-93e2-e9507ad6e746)

### How often does this bug happen?

None

### What is the expected behavior?

// (Object.keys(data) as Array<keyof typeof data>).forEach((key) => {
// 	const value = data[key];
// 	if (typeof key === "string" && (typeof value === "string" || value instanceof Blob)) {
// 		formData.append(key, value);
// 	}
// });

**Comment by stijnvanhulle** [comment]
https://github.com/kubb-labs/kubb/issues/1044

**Comment by stijnvanhulle** [comment]
'v.2.22.1' will resolve this.
