### ISSUE TITLE
An option on swagger-faker plugin to specify the library used to generate regular expressions

### ISSUE THREAD

**Issue by TangoYankee** [kubb-labs/kubb#1067]
### What is the problem this feature would solve?

We are trying to generate mock network responses with fake data that complies with our OpenAPI specification. Our OpenAPI specification includes regular expression patterns that are not supported by the faker "fromRegExp" method. Ultimately, we are unable to write tests that assert that our functions return data compliant with our OpenAPI specification.

### External documents/projects?

The swagger-faker plugin relies on faker and its [fromRegExp method](https://fakerjs.dev/api/helpers.html#fromregexp). In the faker documenation, it recommends using the [RandExp library](https://github.com/fent/randexp.js) for full regex support.

[anatine/zod-mock](https://www.npmjs.com/package/@anatine/zod-mock) is an unrelated package. It also relies on faker-js. However, it seems to include an example of swapping the faker [fromRegExp helper with the RandExp](https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mock.ts#L131)

### What is the feature you are proposing to solve the problem?

An option to specify which library to use when generating data from regular expression, similar to how dates can be configured using "dateType" and "dateParser". It might be named 'regexGenerator'. When the value is undefined, kubb defaults to using `faker.fromRexExp`. When the value is 'randexp', kubb uses `randexp`. Kubb would still use faker for fields of other data types.

The default option would generate data using faker only
```typescript
import { faker } from "@faker-js/faker";
import type { CommunityDistrict } from "../types/CommunityDistrict";

export function createCommunityDistrict(
  data: NonNullable<Partial<CommunityDistrict>> = {},
): NonNullable<CommunityDistrict> {
  return {
    ...{
      id: faker.helpers.arrayElement<any>([
        faker.string.alpha(),
        faker.helpers.fromRegExp(new RegExp("^([0-9]{2})$")),
      ]),
      title: faker.string.alpha(),
    },
    ...data,
  };
}

```

The 'randexp' option would swap to the randexp library for regex based fields, keeping faker for other data types
```typescript
import { faker } from "@faker-js/faker";
import type { CommunityDistrict } from "../types/CommunityDistrict";
import RandExp from "randexp";

export function createCommunityDistrict(
  data: NonNullable<Partial<CommunityDistrict>> = {},
): NonNullable<CommunityDistrict> {
  return {
    ...{
      id: (new RandExp("^([0-9]{2})$")).gen(),
      title: faker.string.alpha(),
    },
    ...data,
  };
}
```

### What alternatives have you considered?

- Overriding the fields using the "data" option in the `create<thing>` functions. However, when we're using these functions with the mock service workers, the msw handlers are calling the functions without the "data" parameters. This closes off that approach.

- Monkeypatching 'faker.fromRegExp' to use 'randexp'. However, we couldn't find a way to apply it cleanly.

- Refactoring our OpenAPI specification away from unsupported Regular Expression features. This might resolve the immediate testing issue. However, it might also undermine our ability to enforce the data schemas we actually want.

**Comment by stijnvanhulle** [comment]
I opened the following PR: https://github.com/kubb-labs/kubb/pull/1070. This will add a new option called `regexGenerator` where you can chose between 'faker' and 'randExp', that should normally resolve your issue.
