### ISSUE TITLE
Specify the Prefix for the generated requests

### ISSUE THREAD

**Issue by 17hz** [kubb-labs/kubb#1086]
### What is the problem this feature would solve?

How do I specify the **prefix** of the request url, which should be different from the baseURL? The scenario is: when I need to define multiple UserConfigs, it is possible that the request urls generated by the client are duplicate.

### What is the feature you are proposing to solve the problem?

I think that a prefix parameter should be added at the osa layer to transform the original URL, so that subsequent plugins do not need to make any changes.

**Comment by stijnvanhulle** [comment]
You can set all your baseURL's with a prefix inside the swagger file(see servers) and then use `serverIndex` to specify which baseURL you want to use.

```
openapi: 3.0.3
info:
  title: Swagger Example
  description:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://develop.petstore.swagger.io/api
- url: http://release.petstore.swagger.io/api
```


```
import { defineConfig } from '@kubb/core'
import { pluginOas } from '@kubb/plugin-oas'

export default defineConfig([
{
  input: {
    path: './petStore.yaml',
  },
  output: {
    path: './src/gen',
  },
  plugins: [
    pluginOas({
      validate: true,
      output: {
        path: './json',
      },
      serverIndex: 0,
      contentType: 'application/json',
    }),
  ],
},
{
  input: {
    path: './petStore.yaml',
  },
  output: {
    path: './src/gen',
  },
  plugins: [
    pluginOas({
      validate: true,
      output: {
        path: './json',
      },
      serverIndex: 1,
      contentType: 'application/json',
    }),
  ],
}
])
```
