### ISSUE TITLE
@apidevtools/swagger-parser is outdated, OpenApi 3.1 schema validation failed.

### ISSUE THREAD

**Issue by nawbc** [kubb-labs/kubb#1090]
kubb v2.23.3

### What version of `kubb` is running?
   Plugins:      3 successful, 3 total Generated:      57 files      Time:      0.820s     Ended:      Sun Jul 28 2024 17:40:10 GMT+0800     Output:      \apps\app\src\gen

### What platform is your computer?

Windows

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

`tanstack-query` `React`,

### How often does this bug happen?
![image](https://github.com/user-attachments/assets/445fee2b-8fdf-49a7-b22c-04ed7ded96a7)

**Comment by stijnvanhulle** [comment]
@apidevtools/swagger-parser is not being used anymore. We are using `@readme/openapi-parser` for validation. See https://apitools.dev/swagger-parser/online/

**Comment by nawbc** [comment]
> @apidevtools/swagger-parser is not being used anymore. We are using `@readme/openapi-parser` for validation. See https://apitools.dev/swagger-parser/online/

But the errors were thrown in the screenshot. Some OpenAPI fields are validated failed.

**Comment by stijnvanhulle** [comment]
`v2.23.4` will resolve your issue that you had with validation :)
