### ISSUE TITLE
Allow to create query and mutate in same method for @kubb/swagger-tanstack-query

### ISSUE THREAD

**Issue by codelonesomest** [kubb-labs/kubb#1097]
### What is the problem this feature would solve?

 We can utilize the `useQuery` method for lists requiring complex filtering, enabling the use of query features instead of mutation.

### What is the feature you are proposing to solve the problem?

Sometimes we need a list API to use the POST method, but instead, we should assign the api to `useQuery` rather than `useMutate`.

**Comment by stijnvanhulle** [comment]
For that you can use https://www.kubb.dev/plugins/swagger-tanstack-query/#query-methods in combination with https://www.kubb.dev/plugins/swagger-tanstack-query/#override

**Comment by codelonesomest** [comment]
Okay, it works for what I need. Thank you

**Comment by codelonesomest** [comment]
Okay, it works for what I need. Thank you
