### ISSUE TITLE
camelCase conversion for the parameters

### ISSUE THREAD

**Issue by wuyuanyi135** [kubb-labs/kubb#1098]
### What is the problem this feature would solve?

Hi, my spec are generated from fastapi. Following pep8, the spec are generated using `snake_case`. Sample of the generated spec json:
```json
"InviteDeviceResponse": {
                "properties": {
                    "success": {
                        "type": "boolean",
                        "title": "Success"
                    },
                    "ipv4": {
                        "type": "string",
                        "title": "Ipv4"
                    },
                    "error_message": {
                        "type": "string",
                        "title": "Error Message"
                    }
                },
                "type": "object",
                "required": [
                    "success"
                ],
                "title": "InviteDeviceResponse"
            },
```

If there is an option to enable camcelCase conversion, the generated stub should convert `error_message` into `errorMessage`

**Comment by stijnvanhulle** [comment]
@wuyuanyi135 I would suggest using [openapi-format](https://github.com/thim81/openapi-format?tab=readme-ov-file#cli-casing-usage) before providing your schema to Kubb(this will make sure your Swagger/openAPI file already has the correct casing).
