### ISSUE TITLE
Mutation using formData does not have proper type

### ISSUE THREAD

**Issue by wuyuanyi135** [kubb-labs/kubb#1099]
### What version of `kubb` is running?

2.24.0 and canary (0.0.0-canary-20240730194937)

### What platform is your computer?

Windows

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

    "@kubb/cli": "^0.0.0-canary-20240730194937",     "@kubb/core": "^0.0.0-canary-20240730194937",     "@kubb/plugin-oas": "^0.0.0-canary-20240730194937",     "@kubb/swagger": "^0.0.0-canary-20240730194937",     "@kubb/swagger-client": "^0.0.0-canary-20240730194937",     "@kubb/swagger-tanstack-query": "^0.0.0-canary-20240730194937",     "@kubb/swagger-ts": "^0.0.0-canary-20240730194937",

### What steps can reproduce the bug?

Generating a mutation with formData (post body) leads to incorrect types.

The following image shows an example of the conflicting logic of using `FormData`: the passed in `data` is a `FormData` but it was re-assembled in the generated hook function.
![image](https://github.com/user-attachments/assets/1de1c39d-796a-47ba-bb38-4403d425e691)

I believe the original thought was to pass in a typed object rather than formData. Tracking down how the type `XXXX['request']` is defined, see the following image:
![image](https://github.com/user-attachments/assets/8fc6e921-446a-4fa4-9b73-e55095a8f3f7)

Obviously, the request type should not be plain `FormData`, the correct type should be the one as shown below
![image](https://github.com/user-attachments/assets/eeb922cb-a20f-4d2e-b9f2-0ba489a2a182)

The issue was originated from https://github.com/kubb-labs/kubb/blob/03938ea4da087d2b39e4176186e360521c7924be/packages/swagger-tanstack-query/src/components/SchemaType.tsx#L46C36-L46C44

I think there is no need to switch types of request here since the `FormData` has been handled in the generated code. Here maybe just using `TRequest` is fine?

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
In v3 of Kubb this has been rewritten and also means the issue you have here would not happen again. I need to see if it would be possible to port the same logic back to v2

**Comment by wuyuanyi135** [comment]
@stijnvanhulle Great to hear! Thank you for the efforts!

**Comment by stijnvanhulle** [comment]
@wuyuanyi135 This has been resolved as part of Kubb v3, see https://github.com/kubb-project/kubb/blob/6f300a90a63e312d2473cd18834f93dca4e9f89e/packages/plugin-client/client.ts where data is not an union of `TData` and `FormData`. The type helper that we had before has also been removed in v3.
