### ISSUE TITLE
Invalid ts code is generated when 'oneOf' is present

### ISSUE THREAD

**Issue by cpr-dev** [kubb-labs/kubb#1108]
### What version of `kubb` is running?

2.22.0

### What platform is your computer?

Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

N/A

### What steps can reproduce the bug?

I'm considering to use Kubb for the first time, and I was playing around with the Playground (https://kubb.dev/playground).

I copy/paste this openApi specification [swagger(3).json](https://github.com/user-attachments/files/16499778/swagger.3.json).

I noticed some weird code being generated for types that use 'OneOf'

example:
``` 
"addressKeyType": {
        "oneOf": [
          {
            "type": "object",
            "title": "Temporary",
            "properties": {
              "temporaryAddressKey": {
                "type": "null"
              }
            }
          },
          {
            "type": "object",
            "title": "Recognised",
            "properties": {
              "recognisedAddressKey": {
                "type": "null"
              }
            }
          }
        ]
      }
```
will be translated to :

```
export const addressKeyTypeSchema = z.union([z.object({ "temporaryAddressKey": .optional(), z, : .null() }), z.object({ "recognisedAddressKey": .optional(), z, : .null() })]);
```

which will lead to ts errors.

### How often does this bug happen?

Every time

### What is the expected behavior?

to have a valid code eg.:
```
export const AddressKeyType = z.union(
    [
      z.object({ 'temporaryAddressKey': z.optional() }),
      z.object({ 'recognisedAddressKey': z.optional() })
    ]) as z.ZodType<AddressKeyType>;
```

### Swagger/OpenAPI file?

[swagger(3).json](https://github.com/user-attachments/files/16499778/swagger.3.json)

**Comment by stijnvanhulle** [comment]
Type `null` is not valid so that is why Kubb will create some weird code. I added a warning so you could see it in the logs but here it seems that you need to validate first your swagger so it is valid OpenAPI v3.

See https://swagger.io/docs/specification/data-models/data-types/
