### ISSUE TITLE
Allow disabling `group.exportAs` from `@kubb/swagger-tanstack-query`

### ISSUE THREAD

**Issue by g-otn** [kubb-labs/kubb#1111]
### What is the problem this feature would solve?

First, thank you all for the great work in this project, this toolkit is great!

When generating queries/mutations with `@kubb/swagger-tanstack-query`, using the `group` options is nice due to the file structure.

However, I couldn't find a way to disable the `group.exportAs` feature, which creates named exports for each group:
```ts
export * as {{tag}}Hooks from './{{tag}}'
```

This makes it verbose to use the hooks, especially if the tag is long:
```ts
myLongTagNameForUserHooks.useMyLongTagNameForUserGetById()
```

This might also probably break some bundle optimizations since the hooks are now object properties, loading all JS referenced in that object when importing.

### What is the feature you are proposing to solve the problem?

Add an option to disable the named export by group feature in the `pluginTanstackQuery` options, such as `group.exportAs: false`, while still keeping the group file structure and respecting `output.exportType`.

### What alternatives have you considered?

For now, I'm simply omitting `group` options so the main `index.ts` file from this plugin doesn't have the named exports.

**Comment by stijnvanhulle** [comment]
@g-otn In v3 of Kubb will `group.exportAs` be removed as a generic option for grouping. The `plugin-client` will still use grouping so controllers can be created that contain `get`, `post`,  `put`, ... for operation x.

**Comment by g-otn** [comment]
v3 is great :)
