### ISSUE TITLE
Kubb v3 ideas

### ISSUE THREAD

**Issue by stijnvanhulle** [kubb-labs/kubb#1115]
I am already thinking about the next version of Kubb and what should be done to make it better:

* [x] Create sponsorship page and readme
* [x] Use the same naming for all plugins: `@kubb/plugin-ts` instead of `@kubb/swagger-ts`
* [x] Drop support of Zodios
* [x] Progressbar for the writing of files
* [x] Progressbar for the hooks of a KubbPlugin(buildStart, buildEnd, ...)
* [x] #1263
* [x] Better debug logs(kubb-files.log and kubb.log) https://github.com/kubb-labs/kubb/pull/1171
* [x] #1152
* [x] #1153
* [x] Removing generic overrides like `transform`, `resolveId` and `writeFile`
* [x] Introduction of global `output.exportType` to customize root barrel generation
* [x] `ouput` options as part of every Kubb plugin
* [x] Validate extName
* [x] enumType `asPascalConst` marked as deprecated
* [x] https://github.com/kubb-labs/kubb/issues/1121
* [x] #1154
* [x] Fix barrel named files(export * from)
* [x] exportType `barrelNamed` as default instead of `barrel`
* [x] #1155
* [x] #1156
* [x] #1157
* [x] #1158
* [x] #1149
* [x] Better docs examples with https://codehike.org/docs
* [x] #1186
* [x] #1189
* [x] https://github.com/kubb-labs/kubb/issues/1102
* [x] #1248
* [x] TypeScipt Strict
* [x] Use of data object for mutations
* [x] #1262
* [x] https://github.com/kubb-labs/kubb/issues/1114
* [x] Improve grouping by `tag`
* [x] https://github.com/kubb-labs/kubb/issues/1281
* [x] https://github.com/kubb-labs/kubb/issues/1195
* [x] Disable `useQuery` generation

https://rollupjs.org/plugin-development/#banner
https://unplugin.unjs.io/guide
https://coolify.io/docs/knowledge-base/faq

**Comment by dir** [comment]
On your note of 

> "Use of the same naming for all plugins: `@kubb/plugin-ts` instead of `@kubb/swagger-ts`, prefix plugin is important here."

In a similar vain, I strongly feel that the use of "swagger" _anywhere_ should be vaulted and replaced with openapi.

I know it seems small, but seeing swagger used instead of openapi gives off a strong "stuck in the past" vibe, for an otherwise such modern and forward thinking library.

**Comment by 1saifj** [comment]
react-form-hook?

**Comment by joakimstrandell** [comment]
@stijnvanhulle Will it be possible to set the basePath for the client dynamically in v3? Would be a dealbreaker if you could set the basePath at runtime, not at generation.

**Comment by stijnvanhulle** [comment]
@joakimstrandell Today(in v2 and v3) you can use `serverIndex` to set the baseUrl: https://www.kubb.dev/plugins/plugin-oas/#serverindex. Other plugins like the `@kubb/plugin-client` and `@kubb/plugin-react-query` will use that config to set the baseURL, would that be enough or what do you mean with **dynamically**?

**Comment by joakimstrandell** [comment]
@stijnvanhulle I mean that I would like to set the path in the client during runtime, for example using some type of custom config. If I would use the server index I need to select the path when generating the client, if I understand the documentation correctly.

For example in hey-api you can set the base url like this:

```ts
import { client } from 'api';
import { config } from  'data' // custom

client.setConfig({
  baseUrl: config.api.basePath,
  headers: {
    Authorization: '...',
    'X-Csrftoken': '...',
  },
});
```

**Comment by stijnvanhulle** [comment]
@joakimstrandell I updated the default `client` to also have `getConfig` and `setConfig` but in Kubb you can also override the default client. This means you can do whatever you want so long you are following the guideline where the parameters are having the same shape as `RequestConfig`.

```
type RequestConfig<TData = unknown> = {
  baseURL?: string
  url?: string
  method: 'GET' | 'PUT' | 'PATCH' | 'POST' | 'DELETE' | 'OPTIONS'
  params?: unknown
  data?: TData | FormData
  responseType?: 'arraybuffer' | 'blob' | 'document' | 'json' | 'text' | 'stream'
  signal?: AbortSignal
  headers?: AxiosRequestConfig['headers']
}
```

**Comment by RabbitShare** [comment]
Transform snake_case to camelCase in generated code. Transform camelCase to snake_case before request

**Comment by stijnvanhulle** [comment]
@RabbitShare For that I suggest using https://github.com/thim81/openapi-format

**Comment by CHE1RON** [comment]
I cannot find any resource (issue, discussion) on why `asPascalConst` is being deprecated .. ? 🤔

**Comment by stijnvanhulle** [comment]
Completing the migration guide before the v3 release: https://v3.kubb.dev/migration-guide. No additional features planned, only bug fixes until the release of v3.
