### ISSUE TITLE
Support discriminators 

### ISSUE THREAD

**Issue by vitorcamachoo** [kubb-labs/kubb#1121]
### What is the problem this feature would solve?

Our API is using the discriminators feature from the open API and Kubb does not support that making a possible migration to this tool impossible. 
Supporting discriminators would be really useful for the community.
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by helt** [comment]
@vitorcamachoo can you provide details where the current behavior of kubb is not as you expected? Ideally with a minimal schema that replicates the issue(s)?

**Comment by vitorcamachoo** [comment]
For the following schema:
```yaml
---
openapi: 3.0.3
components:
  schemas:
    IssueEventParameters:
      type: object
      anyOf:
        - '$ref': '#/components/schemas/IssueEventParametersAcceptAssignment'
        - '$ref': '#/components/schemas/IssueEventParametersAddApprover'
        - '$ref': '#/components/schemas/IssueEventParametersAddTeam'
      discriminator:
        propertyName: eventType
        mapping:
          accept_assignment: '#/components/schemas/IssueEventParametersAcceptAssignment'
          add_approver: '#/components/schemas/IssueEventParametersAddApprover'
          add_team: '#/components/schemas/IssueEventParametersAddTeam'          
```

With the current Kubb version, it is being generated the following code:
```tsx
import { IssueEventParametersAcceptAssignmentSchema } from './issueEventParametersAcceptAssignmentSchema';
import { IssueEventParametersAddApproverSchema } from './issueEventParametersAddApproverSchema';
import { IssueEventParametersAddTeamSchema } from './issueEventParametersAddTeamSchema';

export type IssueEventParametersSchema =
  | IssueEventParametersAcceptAssignmentSchema
  | IssueEventParametersAddApproverSchema
  | IssueEventParametersAddTeamSchema;
```

```tsx
file: issueEventParametersAcceptAssignmentSchema

export type IssueEventParametersAcceptAssignmentSchema = {
  /**
   * @type object
   */
  parameters: {
    /**
     * @type string | undefined, uuid
     */
    issueAssignmentId?: string;
  };
};
```

The expectation of this last piece of code should be the following (it is missing the eventType property):
```tsx
import type { IssueEventParametersAcceptAssignmentSchemaEventType } from './issueEventParametersAcceptAssignmentSchemaEventType';
import type { IssueEventParametersAcceptAssignmentSchemaParameters } from './issueEventParametersAcceptAssignmentSchemaParameters';

export interface IssueEventParametersAcceptAssignmentSchema {
  eventType: IssueEventParametersAcceptAssignmentSchemaEventType;
  parameters: IssueEventParametersAcceptAssignmentSchemaParameters;
}
```

**Comment by stijnvanhulle** [comment]
Some docs:

- https://redocly.com/docs/resources/discriminator
- https://gist.github.com/vrialland/7031316121cb8e025dfca9dccfc226b1

**Comment by stijnvanhulle** [comment]
@vitorcamachoo Can you provide my your swagger/openAPI(or a stripped down version) because I tried with the following example: https://gist.github.com/vrialland/7031316121cb8e025dfca9dccfc226b1 and that works just fine so not sure what we are missing or need to adapt.

**Comment by stijnvanhulle** [comment]
@helt @vitorcamachoo `v2.27.0` has been released with support for discriminators.
