### ISSUE TITLE
you can move mutationFn into a separate function, similar to useQuery requests via queryOptions

### ISSUE THREAD

**Issue by motionrus** [kubb-labs/kubb#1123]
### What is the problem this feature would solve?

I want to use [queryClient.setMutationDefaults](https://tanstack.com/query/latest/docs/reference/QueryClient#queryclientsetmutationdefaults)

and I want the function to be moved out in a similar way to useQuery

```ts
queryClient.setMutationDefaults(['addPost'], { mutationFn: addPost })

function Component() {
  const { data } = useMutation({ mutationKey: ['addPost'] })
}
```

**Comment by stijnvanhulle** [comment]
Closing this one because we have a duplicated ticket for this already: https://github.com/kubb-labs/kubb/issues/1102
