### ISSUE TITLE
Discussion about Kubbs future

### ISSUE THREAD

**Issue by stijnvanhulle** [kubb-labs/kubb#1124]
After 2 years working on Kubb, I decided to _deprecate_ Kubb. I started this project as a hobby project to make it possible to generate code based on a specific input. I looked at some plugin systems like Webpack and Rollup and took some of their concepts to create Kubb plugins. This made it possible to separate the logic and develop plugins per use cases.

After that, I had a look at how Kubb's core could be used to transform a Swagger/OpenAPI file to generate code. Thinking about a plugin that could generate types, React-Query hooks, Zod schemas and so on. After some refactoring and rethinking about the core of Kubb, I came up with a system of plugins(one for ts, one for React-Query, ..). That made it easy to update plugin x without the need to make changes in the core of Kubb. For v1 of Kubb that was working fine but more and more I was getting questions about customizations and that is why in v2 I created a new feature called 'templates'.

Templates made it possible to use JSX to create files, use hooks to retrieve information of a specific operation in the Oas/Swagger but that also made it more complex to onboard new maintainers. Suddenly, you also needed to understand how templates work to make changes in Kubb. 
I still believe that templates could be something useful to create files based on what most React developers already know: JSX. But that was probably not the perfect change because that made Kubb a little bit harder to understand. 

Those 2 layers are also why I had the idea with v3 of Kubb to change that. By removing templates and unnecessary parts so I could create a version that was only focused on the OpenAPI/Swagger to js/ts files. But refactoring this would take some time and doing this on my own would not be possible. I'm quite occupied with my job as front-end lead and I'm also planning to start a photography 📷 business soon.

So that's why I thought about deprecating Kubb and forwarding all developers to use [Orval](https://github.com/orval-labs/orval) instead.

I had a lot of fun creating Kubb and learned a lot about generation and Oas but sadly this will be the end of Kubb. 👋🏽

> Update: after some discussions with some of you I decided to revert the deprecation warnings and take the opportunity to share more about how Kubb works with some of you that want to help out and contribute. This means Kubb is not dead but for the moment no feature will be added until everything has been cleared out. This means there is still a chance that a v3 of Kubb will come but I will leave that up to the community what will be included.

[Stijn](https://github.com/stijnvanhulle)

**Comment by motionrus** [comment]
I'm sorry to hear that, I really appreciate the contribution you're making and I really hope you have some free time to keep working on this project. It's the best project I've ever seen. Very competent approach to development, it's a source of inspiration for me. Good luck!

**Comment by omridevk** [comment]
@stijnvanhulle 
Couldn't agree with @motionrus more, really awesome work and looking forward to using your next project, as I wasn't able to yet use this one!

**Comment by samchon** [comment]
How about `@nestia/editor` case? 

It also supports every versions of OpenAPI, and provides mockup simulator too.

https://nestia.io/docs/editor/

**Comment by Samuel-Morgan-Tyghe** [comment]
This is a sad time, I have been working with kubb for the last 6 months , its a brilliant tool and was the creme de la creme of value I brought to my company.

**Comment by helt** [comment]
Thank you a lot for your efforts you've put into kubb. It helped me a lot and it was a pleasure contributing. But I also want to thank you for announing the deprecation and not just orphan it.

**Comment by t1mmen** [comment]
I only recently discovered Kubb, and it's been working perfectly for us!

Unfortunate (for me) to see this deprecation notice, though I appreciate the up-front decision and transparency. Thank you very much for making it in the first place! Best of luck!

**Comment by shinebayar-g** [comment]
> so I could create a version that was only focused on the OpenAPI/Swagger to js/ts files.

+1 on this. Kubb provides much value. But the `@kubb/core` library still feels heavy at 1.45MB..
