### ISSUE TITLE
Combined changelog on kubb site?

### ISSUE THREAD

**Issue by helt** [kubb-labs/kubb#1135]
### What is the type of issue?

Documentation is confusing

### What is the issue?

Normally, for crucial packages, I scan the changelogs prior upgrading. However, for kubb it's a pain to sift through the changelogs of kubb. It would be great to have relevant changes (excluding deps updates) consolidated in 1 place. Maybe this exists already, but I haven't found it.

Also, a good changelog is increasing trust for potential users of kubb.

**Comment by stijnvanhulle** [comment]
We have a changelog per plugin/package but those contain a lot of internal notes so a solution here could be to add changelog notes to the Kubb docs. Maybe something like eslint does: https://eslint.org/blog/2024/08/eslint-v9.9.1-released/?

**Comment by helt** [comment]
yeah something along those lines would be great.

**Comment by IanVS** [comment]
FWIW, the link is now https://kubb.dev/changelog in case anyone else is looking for it.
