### ISSUE TITLE
Zod parser with @kubb/swagger-tanstack-query, dataReturnType "full" and a custom client (ky)

### ISSUE THREAD

**Issue by filipjakov** [kubb-labs/kubb#1145]
### What version of `kubb` is running?

2.25.2

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

2.25.2

### What steps can reproduce the bug?

- add the zod plugin 
- add the react query plugin with `parser: "zod"` and `dataReturnType: 'full'` (to comply with the custom client that is not "axios-like")
- add a custom client (ky in my example) that is not Axios compliant:

```ts
import ky from 'ky';
import type { HttpMethod } from 'ky/distribution/types/options';

export interface RequestConfig<TVariables = unknown> {
	method: HttpMethod;
	url: string;
	params?: unknown;
	data?: TVariables;
	// responseType?: 'arraybuffer' | 'blob' | 'document' | 'json' | 'stream' | 'text';
	signal?: AbortSignal;
	headers?: Record<string, string>;
}

export const kyInstance = ky.extend({
	retry: 0,
	prefixUrl: '/api',
	credentials: 'include',
});

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const kyAxiosAdapter = async <TData, _TError = unknown, TVariables = unknown>({
	url,
	...rest
}: RequestConfig<TVariables>): Promise<TData> => {
	const method = kyInstance[rest.method];

	return method<TData>(url, { ...rest }).json();
};

export default kyAxiosAdapter;
```

- generated hooks still try to access `res.data` for zod parsing:

```tsx
export function showPetByIdQueryOptions(
	petId: ShowPetByIdPathParams['petId'],
	options: ShowPetById['client']['parameters'] = {}
) {
	const queryKey = showPetByIdQueryKey(petId);
	return queryOptions({
		queryKey,
		queryFn: async () => {
			const res = await client<ShowPetById['data'], ShowPetById['error']>({
				method: 'get',
				url: `/pets/${petId}`,
				...options,
			});
			return { ...res, data: showPetByIdQueryResponseSchema.parse(res.data) }; // <-- error `Property 'data' does not exist on type `
		},
	});
}
```

### How often does this bug happen?

Every time

### What is the expected behavior?

The generated code should take into account `dataReturnType "full"` from the RQ options

### Swagger/OpenAPI file?

{
	"openapi": "3.0.0",
	"info": {
		"version": "1.0.0",
		"title": "Swagger Petstore",
		"license": {
			"name": "MIT"
		}
	},
	"servers": [
		{
			"url": "http://petstore.swagger.io/v1"
		}
	],
	"paths": {
		"/pets": {
			"get": {
				"summary": "List all pets",
				"operationId": "listPets",
				"tags": ["pets"],
				"parameters": [
					{
						"name": "limit",
						"in": "query",
						"description": "How many items to return at one time (max 100)",
						"required": false,
						"schema": {
							"type": "integer",
							"maximum": 100,
							"format": "int32"
						}
					}
				],
				"responses": {
					"200": {
						"description": "A paged array of pets",
						"headers": {
							"x-next": {
								"description": "A link to the next page of responses",
								"schema": {
									"type": "string"
								}
							}
						},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Pets"
								}
							}
						}
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create a pet",
				"operationId": "createPets",
				"tags": ["pets"],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Pet"
							}
						}
					},
					"required": true
				},
				"responses": {
					"201": {
						"description": "Null response"
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			}
		},
		"/pets/{petId}": {
			"get": {
				"summary": "Info for a specific pet",
				"operationId": "showPetById",
				"tags": ["pets"],
				"parameters": [
					{
						"name": "petId",
						"in": "path",
						"required": true,
						"description": "The id of the pet to retrieve",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Expected response to a valid request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Pet"
								}
							}
						}
					},
					"default": {
						"description": "unexpected error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"Pet": {
				"type": "object",
				"required": ["id", "name"],
				"properties": {
					"id": {
						"type": "integer",
						"format": "int64"
					},
					"name": {
						"type": "string"
					},
					"tag": {
						"type": "string"
					}
				}
			},
			"Pets": {
				"type": "array",
				"maxItems": 100,
				"items": {
					"$ref": "#/components/schemas/Pet"
				}
			},
			"Error": {
				"type": "object",
				"required": ["code", "message"],
				"properties": {
					"code": {
						"type": "integer",
						"format": "int32"
					},
					"message": {
						"type": "string"
					}
				}
			}
		}
	}
}

### Additional information

Is there a config option i could be missing?

**Comment by stijnvanhulle** [comment]
`dataReturnType` can switch between return `res.data` or just `res` (response). 
But your client should always return the type `ResponseConfig` which will be an object with data and status as properties. So the client will always be made with `dataReturnType: 'full'` in mind but our plugins will change based on that property to use res.data or data. See https://v3.kubb.dev/knowledge-base/how-tos/fetch.

```
import ky from 'ky';
import type { HttpMethod } from 'ky/distribution/types/options';

export interface RequestConfig<TVariables = unknown> {
	method: HttpMethod;
	url: string;
	params?: unknown;
	data?: TVariables;
	// responseType?: 'arraybuffer' | 'blob' | 'document' | 'json' | 'stream' | 'text';
	signal?: AbortSignal;
	headers?: Record<string, string>;
}
// add this
export type ResponseConfig<TData = unknown> = {
  data: TData
  status: number
}

export const kyInstance = ky.extend({
	retry: 0,
	prefixUrl: '/api',
	credentials: 'include',
});

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const kyAxiosAdapter = async <TData, _TError = unknown, TVariables = unknown>({
	url,
	...rest
}: RequestConfig<TVariables>): Promise<ResponseConfig<TData>> => {
	const method = kyInstance[rest.method];
        const data = method<TData>(url, { ...rest }).json();

	return {
           data,
           status: 200
        }
};

export default kyAxiosAdapter;
```
