### ISSUE TITLE
Infinite recursion with Faker when a component includes itself

### ISSUE THREAD

**Issue by g-gagnon** [kubb-labs/kubb#1165]
### What version of `kubb` is running?

kubb/2.16.3 darwin-arm64 node-v20.10.0

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

I have a component called Account, and it has a child_accounts properties defined as such:
```
properties:
    child_accounts:
    type: array
    items:
      $ref: ./Account.yaml
```
(Note that having the reference as `$ref: '#'` does not change anything).

The generated mock for `createAccount` then include this properties: `child_accounts: faker.helpers.arrayElements([createAccount()]) as any`, which goes into a infinite recursion loop that ends up in a stack level error.

### How often does this bug happen?

Every time

### What is the expected behavior?

I'm not sure what a clean solution for this would look like, the workaround I have for now is to create a `ChildAccount` component and have that component not have the child_accounts property. Not perfect since it will only return one level of nested accounts.

Thank you for all the support, much appreciated!

**Comment by stijnvanhulle** [comment]
Both `$ref: ./Account.yaml` and `$ref: '#'` will reference to the current file which means with a type as array you will see an infinite loop. We are using behind-the-scenes https://github.com/Mermade/oas-kit/blob/main/packages/swagger2openapi/README.md to convert v2 Swagger files to the OpenAPI v3.

What you can do here is define 2 schemas(one for account and one for accounts):
```
components:
  schemas:
   account:  
     type: string
    accounts:
      type: array
      xml:
        name: addresses
        wrapped: true
      items:
        $ref: "#/components/schemas/account"
```

**Comment by g-gagnon** [comment]
The issue still remains, since given the component tree you account is an object, missing child_accounts. I tried the following:
```
components:
  schemas:
   account:  
     type: object
     properties:
       child_accounts: 
         $ref: "#/components/schemas/accounts"
    accounts:
      type: array
      xml:
        name: addresses
        wrapped: true
      items:
        $ref: "#/components/schemas/account"
```

But that still generate faker mocks that calls each other (removed other properties of account for brevity):

```
export function createAccount(
  data: NonNullable<Partial<Account>> = {},
): NonNullable<Account> {
  return {
    ...{
      child_accounts: createAccounts(),
    },
    ...data,
  };
}

export function createAccounts(
  data: NonNullable<Partial<Accounts>> = [],
): NonNullable<Accounts> {
  return [...(faker.helpers.arrayElements([createAccount()]) as any), ...data];
}
```

This issue seems specific to the Faker plugin. The doc generated by redocly for example does not allow you to "expand" child_account definition because I assume they detect the loop
![image](https://github.com/user-attachments/assets/8669921f-2b06-4f7c-adbc-c09e8a0433e3)

The only solution that would make sense to me is when mocks are generated, if the object type that is to be created is already present in the ancestor tree, then pass `undefined` or empty array depending of the type of field it is. So in my case, child_accounts would not call createAccount() because Account is already one of the parent.

I understand this is a edge case, and potentially a pain to fix assuming I've done things properly. I found a workaround that limits my nesting, but I don't think it's gonna impact my app so it's not a dealbreaker on my side.

**Comment by stijnvanhulle** [comment]
The issue here is that you have a circular reference, I tried with a dereference before providing the schema to the **faker** plugin but that resulted again in the same issue. For this, I don't see an easy fix, and also not sure if it is even fixable because the issue is more or less on the javascript side. Kubb just generated files so it does not keep track of the call history + there is no way for us to see where we need to limit this(probably more bugs will come up if we try to guess).

Something like this will probably mean a manual faker mock should be created instead to have control over the number of levels that need to be mocked.

See https://apitools.dev/swagger-parser/docs/#circular-refs.
