### ISSUE TITLE
Generate code using native `fetch` for nextjs SSR

### ISSUE THREAD

**Issue by abdelrahman-essawy** [kubb-labs/kubb#1178]
### What is the problem this feature would solve?

Nextjs (App dir) SSR method requires the use of the native `fetch`.

### External documents/projects?

https://nextjs.org/docs/app/api-reference/functions/fetch

### What is the feature you are proposing to solve the problem?

adding a way to use the native `fetch` instead of `axios`, `tanstack`, etc.

**Comment by stijnvanhulle** [comment]
I added the following wiki page: https://v3.kubb.dev/knowledge-base/how-tos/fetch. This is for v3 but v2(the current stable version) could use the same setup. I hope this could help you out using Fetch in Nextjs.
