### ISSUE TITLE
Request an option: function object-style parameters.

### ISSUE THREAD

**Issue by lakca** [kubb-labs/kubb#1195]
### What is the problem this feature would solve?

Expect an alternative:

```typescript
type Options = {
	name: string,
	params: {/*...*/},
	headers: {/*...*/},
	/* ... */ 
}

function xxx(options: Options) {}
```

Currently only:

```typescript
type Options = {
	name: Name,
	params: SomeParams,
	headers: SomeHeaders,
	/* ... */
}

function xxx(name: Name, params: SomeParams, headers: SomeHeaders) {}
```

### What is the feature you are proposing to solve the problem?

Avoid redundant `undefined` to occupy positions when you don't need to provide intermediate parameters, just likes `func('a value', undefined, undefined, 'a value')`

**Comment by stijnvanhulle** [comment]
@lakca in Kubb v`3.0.0-beta-10` we added `paramsType`, with this option you can switch between object-style parameters and multiple inline parameters.

https://v3.kubb.dev/plugins/plugin-react-query/#paramstype
