### ISSUE TITLE
Kubb working only with react 18

### ISSUE THREAD

**Issue by RabbitShare** [kubb-labs/kubb#1219]
### What is the type of issue?

Documentation is missing

### What is the issue?

Environment section does not contain  React version restriction
<img width="717" alt="image" src="https://github.com/user-attachments/assets/696bd9b5-2756-48a6-aec2-cd9a29ee15e1">

In react 17 error
<img width="733" alt="image" src="https://github.com/user-attachments/assets/84d5686d-d920-4918-b7df-b515638786a4">

**Comment by stijnvanhulle** [comment]
React is part of Kubb so normally you dont need to specify a React version. Which version of Kubb are you using and can you provide me a simple playground/example?

**Comment by RabbitShare** [comment]
I found problem https://github.com/facebook/react/issues/20235#issuecomment-861836181. It's not a kubb problem

**Comment by RabbitShare** [comment]
With this tsconfig working great

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["kubb.config.ts"]
}
```
