### ISSUE TITLE
@kubb/swagger-ts => readOnly attributes using $refs not flagged as readonly

### ISSUE THREAD

**Issue by MetaCrawler** [kubb-labs/kubb#1220]
### What version of `kubb` is running?

2.26.3

### What platform is your computer?

Windows + WSL2 (Ubuntu 22.04.1 LTS) + VsCode + Devcontainer (Debian 11)

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"@tanstack/vue-query": "^5.56.2", "vue": "^3.4.21", "@kubb/cli": "^2.26.3",     "@kubb/core": "^2.26.3",     "@kubb/plugin-oas": "^2.26.3",     "@kubb/swagger-client": "^2.26.3",     "@kubb/swagger-tanstack-query": "^2.26.3",     "@kubb/swagger-ts": "^2.26.3",

### What steps can reproduce the bug?

1) Use the attached demo.json
2) Use the attached kubb.client.ts
3) run kubb

### How often does this bug happen?

Every time

### What is the expected behavior?

1) Attributes should be properly marked as readonly in the type definition.
2) Having different type definitions for Requests and Responses (suggestion)

### Swagger/OpenAPI file?

Dumped down demo.json to reproduce:
[demo.json](https://github.com/user-attachments/files/17042603/demo.json)

Demo kubb.config.ts:
[kubb.config.ts.txt](https://github.com/user-attachments/files/17042418/kubb.config.ts.txt)

### Additional information

Hello, maybe I'm having a big missunderstanding here, or I have a wrong swagger file...
Or if this is more of a feature than a bug...

Anyway:
Swagger json or yaml are generating incorrect Types, 
specifically when attributes are defined as readOnly and using refs in the definition file.

When I look at the specification:
https://swagger.io/docs/specification/data-models/data-types/#readonly-writeonly

> You can use the readOnly and writeOnly keywords to mark specific properties as read-only or write-only. This is useful, for example, when GET returns more properties than used in POST – you can use the same schema in both GET and POST and mark the extra properties as readOnly. readOnly properties are included in responses but not in requests, and writeOnly properties may be sent in requests but not in responses. 

> If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only. 

Maybe I do not understand above correctly, but attached files are generating following types:
```ts
import type { AttributeWithRef } from "./AttributeWithRef";
import type { AttributeWithRefReadonly } from "./AttributeWithRefReadonly";
import type { AttributeWithRefReadonlyRequired } from "./AttributeWithRefReadonlyRequired";

 export type Demo = {
    readonly attribute_readonly_required: number;
    readonly attribute_readonly_not_required?: number;
    attribute: number;
    attribute_with_ref?: AttributeWithRef;
    attribute_with_ref_readonly: AttributeWithRefReadonly;
    attribute_with_ref_readonly_required: AttributeWithRefReadonlyRequired;
};
```

Questions from my side: 
1) attribute_with_ref_readonly => missing readonly?
2) attribute_with_ref_readonly_required => missing readonly?
3) Shouldnt there bascially two "Demo" Types? Like "DemoRequest" and "DemoResponse"? With different attributes which are required depending on the readOnly and writeOnly settings?

For example "DemoRequest": 
```ts
`import type { AttributeWithRef } from "./AttributeWithRef";

 export type DemoRequest = {
    attribute: number;
    attribute_with_ref?: AttributeWithRef;
};
```

Because in the "Request" the readonly properties are not needed, and as described in the above spec, because these a different "scopes"... and when using the current type definition inside my code, typescript throws an error that I need to define the readonly attributes in my object.

I mean, what I now do as a workaround is:
```ts
type DemoRequest = Omit<Demo, 'attribute_readonly_required' | 'allOtherReadonlyAttributes'>
const demo: DemoRequest = {
 attribute: 'value'
}
const payload = {
    data: demo as Demo
}
 await postDemo(payload).then(() => {
      queryClient.invalidateQueries()
})
```

Its no big issue, but just something I noticed.
Sorry for the wall of text.
Sorry if I understood / did something wrong.

Thank you for any help or comment on that issue.

**Comment by stijnvanhulle** [comment]
@MetaCrawler When an item is a reference it was not resolving the ref itself(only a hard link to it). That meant that `$ref`  was not taking into account the `readOnly` and `writeOnly` fields. I opened a pr to resolve this: https://github.com/kubb-labs/kubb/pull/1241.

**Comment by stijnvanhulle** [comment]
`v2.26.6` will resolve your issue, feel free to reopen when this does not resolve your issue.
Thanks for using Kubb 🥳.
