### ISSUE TITLE
v3 documentation resolves to 404s

### ISSUE THREAD

**Issue by luixo** [kubb-labs/kubb#1224]
### What is the issue?

The main page links to:
[OpenAPI/Swagger](https://v3.kubb.dev/docs/plugins/plugin-oas/)
[Typescript](https://v3.kubb.dev/docs/plugins/plugin-ts)
[Tanstack query](https://v3.kubb.dev/docs/plugins/plugin-tanstack-query)
etc..

All of them resolve to 404 at the moment :(

The same links without `/docs` work all right

**Comment by stijnvanhulle** [comment]
@luixo This should be resolved again, be aware that v3 docs are not finished yet so still some changes will come in the coming weeks.
