### ISSUE TITLE
freeform object is not created correctly in plugin-ts

### ISSUE THREAD

**Issue by grreeenn** [kubb-labs/kubb#1232]
### What version of `kubb` is running?

2.17.0, but works the same with 3.0.0-alpha.20

### What platform is your computer?

macos

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

irrelevant

### What steps can reproduce the bug?

There are two ways to express a "freeform object" in OpenAPI: either add `additionalProperties: true` or `additionalProperties: {}` to the entity with type `object` ([source](https://swagger.io/docs/specification/data-models/dictionaries/#free-form)).

The `plugin-ts` does perfectly fine with former way and generates 
```typescript
freeformObject: {
    [key: string]: any
}
```
which is an accurate way to express an object with keys as strings (as per spec) and any kind of values.

The latter way of expressing the same, `additionalProperties: {}`, has a bug - it generates the following:
```typescript
freeformObject: object
```
which basically says that it can be anything except `null` or `undefined`, but the compiler doesn't know anything about the value, so doing something like `freeformObject['someRandomKey'] = 2` throws `Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'`.

### How often does this bug happen?

None

### What is the expected behavior?

get 
```typescript
freeformObject: {
    [key: string]: any
}
```
in both cases

### Swagger/OpenAPI file?

providing only the relevant part of the slightly changed petStore.yml you use in your project:
```yaml
Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        freeformObject:
          type: object
          additionalProperties: {}
        category:
          $ref: 'https://petstore3.swagger.io/api/v3/openapi.json#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: pet
```

### Additional information

So I went on to dig into what was happening and ended up in `SchemaGenerator.ts` of `plugin-oas`. 
Found the place where it checks for `additionalProperties === true` and added `|| !Object.keys(additionalProperties).length`, hoping for an easy fix; however, it didn't change a thing. 

So I set a breakpoint there and found out that if `additionalProperties` contains `{}`, it gets stripped (the object that gets there is just `{type: 'object'}`, without `additionalProperties` at all); I went on as high as I saw inside the flow and got convinced to a certain degree that it gets stripped in `oas` during the initial parsing.

Unfortunately, I didn't have too much time to play with it, and the code there is not the simplest; if you could direct me to where else I can look to find out the root cause I'd be thankful. And thanks for the great project of course!! :)

**Comment by stijnvanhulle** [comment]
We were using [openapi-format](https://www.npmjs.com/package/openapi-format) which already strips out some data and `preserveEmptyObjects` was set to false. This meant that empty objects were removed from the Oas Schema before it was passed to the `SchemaGenerator.ts`. And that caused that weird issue for you, your solution here will work fine after I remove the experimental format and sorting of [openapi-format](https://www.npmjs.com/package/openapi-format).


See https://github.com/kubb-labs/kubb/pull/1233

**Comment by grreeenn** [comment]
Spectacular, thank you! Shall I open a PR with it then?

**Comment by stijnvanhulle** [comment]
@grreeenn If you want to do that, that would be great :)

**Comment by grreeenn** [comment]
@stijnvanhulle with great pleasure :) I hope I got all the contribution guidelines right. Also, will it get to v2?
