### ISSUE TITLE
@kubb/plugin-zod body schemas should generate with .optional() when they're marked as not required

### ISSUE THREAD

**Issue by mitchell-merry** [kubb-labs/kubb#1249]
### What version of `kubb` is running?

2.26.7

### What steps can reproduce the bug?

See the Swagger file - if a path has a body parameter which is not marked as `required: true`, I would expect that the schema it generates is marked as .optional() so that `undefined` is also a valid value.

It generates:
```
import { z } from 'zod';

export const testOperationMutationRequestSchema = z.object({});

export const testOperationMutationResponseSchema = z.unknown();
```

While I would expect it to generate (see next section)

### How often does this bug happen?

None

### What is the expected behavior?

```ts
import { z } from 'zod';

export const testOperationMutationRequestSchema = z.object({}).optional();

export const testOperationMutationResponseSchema = z.unknown();
```

### Swagger/OpenAPI file?

```yaml
paths:
  /test:
    post:
      operationId: testOperation
      responses: { .. }
      parameters:
        - name: body
          in: body
          required: false
          schema:
            type: object
            properties: {}
```

**Comment by stijnvanhulle** [comment]
@mitchell-merry `in: body` does not exist in Swagger/OpenAPI, see following error after validating your example:
<img width="452" alt="Screenshot 2024-09-23 at 6 57 19 PM" src="https://github.com/user-attachments/assets/a99414d2-bf35-4fa8-9bcd-585ee962623e">

If you want to use a body schema for a POST/PUT call please use `requestBody` instead.

Links:

- https://swagger.io/docs/specification/describing-parameters/
- https://swagger.io/docs/specification/describing-request-body/

**Comment by mitchell-merry** [comment]
It's swagger 2.0, not OpenAPI 3.
