### ISSUE TITLE
Many (all?) of the codesandbox examples are broken

### ISSUE THREAD

**Issue by robert-westenberger** [kubb-labs/kubb#1258]
### What is the type of issue?

Example code is not working

### What is the issue?

The examples on the left sidebar on this page are broken.

https://kubb.dev/examples/simple

When navigating to a code sandbox, I see this:

![image](https://github.com/user-attachments/assets/308c9e79-01f2-478f-bdb7-89b6fdb14809)

I'm not too familiar with code sandbox, not sure what's happening here.

A few other examples, selected at random, have what appears to be an identical issue.

https://codesandbox.io/p/sandbox/github/kubb-labs/kubb/tree/main/examples/client?from-embed

https://codesandbox.io/p/sandbox/github/kubb-labs/kubb/tree/main/examples/msw?from-embed

**Comment by robert-westenberger** [comment]
Just speculating, but it looks like the dependencies in the package.json are listed as pnpm style workspace:* dependencies,

```json
"dependencies": {
    "@kubb/cli": "workspace:*",
    "@kubb/core": "workspace:*",
    "@kubb/plugin-client": "workspace:*",
    "@kubb/plugin-oas": "workspace:*",
    "@kubb/plugin-ts": "workspace:*",
    "@kubb/react": "workspace:*",
    "axios": "^1.7.7"
  },
  "devDependencies": {
    "@kubb/config-ts": "workspace:*",
    "react": "^18.3.1",
    "tsup": "^8.3.0",
    "typescript": "^5.6.2"
  },
```

but those workspaces aren't in the codesandbox itself, nor is there any pnpm-workspace.yaml file. That could have something to do with it.

**Comment by stijnvanhulle** [comment]
@robert-westenberger Thanks for reporting, indeed the workspace syntax should not be there. I updated the script so the workspace is being replaced by a version that can be installed. This has been resolved.

**Comment by robert-westenberger** [comment]
Thank you @stijnvanhulle . Great project.
