### ISSUE TITLE
Zod tuples in incorrect order

### ISSUE THREAD

**Issue by benboothby** [kubb-labs/kubb#1264]
### What version of `kubb` is running?

2.27.0

### What platform is your computer?

Linux

### What steps can reproduce the bug?

https://codesandbox.io/p/devbox/kubb-zod-tuple-example-j75v58

In the example there are two tuple;
- One where there are three numbers and the third should be an int
- And one with mixed data types, where you can see that the ts output is in the correct order but the zod schema is reversed

### How often does this bug happen?

Every time

### What is the expected behavior?

Zod schemas should have the order of tuples preserved.

`[
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "integer"
                  }
 ]`
should become 
`z.tuple([z.number(), z.number(), z.number().int()])`
not
`z.tuple([z.number().int(), z.number(), z.number()])`

**Comment by stijnvanhulle** [comment]
@benboothby Kubb [2.27.1](https://github.com/kubb-labs/kubb/releases/tag/%40kubb%2Fswagger%402.27.1) has been released that will resolve your issue.
