### ISSUE TITLE
Duplicated InfiniteData for react-query v4 in infiniteQueries

### ISSUE THREAD

**Issue by RabbitShare** [kubb-labs/kubb#1293]
### What steps can reproduce the bug?

1. Open kubb example from site https://codesandbox.io/p/devbox/wispy-rgb-sgm8cw?embed=1
2. Find file useFindPetsByStatusHook.ts
3. Write on both of the file
```typescript
type A = typeof useFindPetsByStatusHookInfinite<
  InfiniteData<FindPetsByStatus['response']>
>;

type B = ReturnType<A>;

type C = B['data'];
```
InfiniteData duplicates:
<img width="575" alt="Снимок экрана 2024-10-05 в 02 19 43" src="https://github.com/user-attachments/assets/f4b9d3d0-f099-436b-b58c-941cf2600c53">

### How often does this bug happen?

Every time

### What is the expected behavior?

InfiniteData not duplicates

### Swagger/OpenAPI file?

In sandbox

### Additional information

I think problem with UseInfiniteQueryResult and TData = InfiniteData<FindPetsByStatus['response']>. Using both duplicates InfiniteData
try without InfiniteData:
```typescript
type A = typeof useFindPetsByStatusHookInfinite<FindPetsByStatus['response']>;

type B = ReturnType<A>;

type C = B['data'];
```
Working fine!
<img width="564" alt="image" src="https://github.com/user-attachments/assets/a8e8b7d9-ebb8-4dcc-8403-ec558a170301">

<sub>[KUB-10](https://linear.app/kubb/issue/KUB-10/duplicated-infinitedata-for-react-query-v4-in-infinitequeries)</sub>

**Comment by stijnvanhulle** [comment]
@RabbitShare This has been resolved as part of Kubb v`2.28.1`
