### ISSUE TITLE
Generated mocks fails to match the requirements of Zod

### ISSUE THREAD

**Issue by ekaradon** [kubb-labs/kubb#1335]
### What version of `kubb` is running?

2.27.0

### What platform is your computer?

Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

    "@kubb/cli": "^2.27.0",     "@kubb/core": "^2.27.0",     "@kubb/plugin-oas": "^2.27.0",     "@kubb/swagger": "^2.27.0",     "@kubb/swagger-client": "^2.27.0",     "@kubb/swagger-faker": "^2.27.1",     "@kubb/swagger-msw": "^2.27.1",     "@kubb/swagger-tanstack-query": "^2.27.0",     "@kubb/swagger-ts": "^2.27.0",     "@kubb/swagger-zod": "^2.27.0",

### What steps can reproduce the bug?

Go there:
https://play.kubb.dev/?focus_mode=default&version=2.26.7&tanstack_version=4&msw_version=1&config=H4sIAAAAAAAAA3WPsQ6DMAxE%2F8VzgJ2p%2F9ARMRgIAQXiNHGEKMq%2FN%2BnWNt2s57vT3QWOiKGFGgSsxoZ0X2CRl8waK%2FnO5GR94r5BFECBPzVKmsztFtRqPLRdBzcdhqHxByolHYgr9uILVuwT%2Fw3baZKbr9M3FkxPmoquzEt6RuMZR109gnRn0boQaZ%2F7zw53eZDTCTqJI0MhcEb9HlQqPv7P6eMLtGm2S2YBAAA%3D&code=H4sIAAAAAAAAA51V32%2FaMBB%2Bz19hsUk80bDxlje0ZgNpA9RWm6ppQkdyAVeJ7drOWvbXz44dcFJGWfOEv%2Fvu%2FJ3vB1wgA0ETMrkaX02iiLKCJxEhmuoSEzJYGvt0NSdKYEYLmoGmnJGCS7LiGjRHNTDsHFUmqbA24%2FOZcwv%2BRqkc8MHEHg8ihdJiNvyI1LJMSFxwHgnQuwaMhQ9pD4RsUbsfvfhfqdJE75C0dJLXkrJtg2laIXmiLOdP3pcLlI3qeZ7YmK1ubxYgoULtdblvRJjBEpc0qp%2B%2FDhZCqFHwWKPcB5jKdlhBEiDmAffCRAApYd%2FBqcZKdaktWWmbxgsVOWhcd1L6Hx3vJRYJGb6LM14JzpBpFTueiq9N5B9N4KH3kagMSWGgcPhxPB6GMTvFKG0xeHFhLeyXcaaNiq5KEKL0zRU%2FKBO490CnMnstuy%2FHWg8j76nqqgK5d01kdQbSPUXDttMKQlIuqaZ%2FGnXe8DzyaYx8nXv6DzTIMhRanWH07zPnpH9pdEzPUn2GzutYxDbKiW5CVlfhJXezmzRd36fTm9sAXS4c9oL4bbm4m%2FWZDRhgt%2Bn3dLG%2Bnt474ideVWbo%2FD456Do48M0DZvrQd481lZiHGmneG4V2YqUdaU3DJqV52Bvdi5q6d0erGaxLHBosaKSWBHlObWWgXB3VkAJKhW9M1q6Fcwn218bp%2FXJiu5wbEZeWnw53uKBYUJbLIhTvrhj8a8fAzAwbl%2FtB1DZsi3Q79tVHMpsQ1jvneuatQtqbnswRzchsUHYMrC5L2Ng%2FRi1rDEwVZfMmDpmEKDy36PgvDr9WlWkHAAA%3D

Add the `pluginFaker` to the config and check that the requirements of zod isn't met by the mocks:

```
export function createDataHistory(
  data: NonNullable<Partial<DataHistory>> = {}
): NonNullable<DataHistory> {
  return {
    ...{
      data_history: faker.helpers.arrayElements([faker.number.float()]) as any
    },
    ...data
  }
}
```

Compared to zod requirements:

```
export const dataHistorySchema = z.object({
  data_history: z.array(z.number().nullable()).min(3).max(30)
})
```

### How often does this bug happen?

Every time

### What is the expected behavior?

```
      data_history: Array.from(
        { length: faker.number.int({ min: 3, max: 30 }) },
        () => faker.number.float()     
     ) as any
```

### Swagger/OpenAPI file?

```
openapi: 3.0.3

info:
  title: "OpenAPI specification for Potatoes"
  description: "Foo"
  version: "1.0.0"
servers:
  - url: /foo
paths:
  /potatoes:
    get:
      description: List the potatoes during the time window
      operationId: getPotatoes
      parameters:
        - name: species[]
          in: query
          schema:
            type: array
            items:
              type: string
        - name: date_window
          in: query
          schema:
            $ref: '#/components/schemas/DateWindow'
      responses:
        '200':
          description: list of potatoes during the time window
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPotatoes'

      summary: Listing of potatoes
      tags:
        - prioritization
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
        - tag: prioritization

components:
  schemas:
    DateWindow:
      type: string
      enum:
        - THREE_YEARS
        - ONE_YEAR
        - THREE_MONTHS
        - ONE_MONTH
        - SEVEN_DAYS
    CommonInfo:
      type:
        object
      required:
        - id
        - name
      properties:
        id:
          type:
            string
        name:
          type:
            string

    GetPotatoes:
      additionalProperties: false
      type:
        object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Potato'

    Potato:
      type:
        object
      allOf:
        - $ref: "#/components/schemas/DataHistory"

    DataHistory:
      type: object
      required:
        - data_history
      properties:
        data_history:
          type: array
          items:
            type: number
            nullable: true
          minItems: 3
          maxItems: 30
```

### Additional information

It seems that we need to change the MSW config to also be more strict.

**Comment by stijnvanhulle** [comment]
@ekaradon I changed the generation to use `faker.helpers.multiple` instead, this makes it possible to use `min` and `max, see https://fakerjs.dev/api/helpers#multiple.

**Comment by ekaradon** [comment]
Nice! Thanks for the quick fix! :smile:
