### ISSUE TITLE
QueryImports is not exported yet

### ISSUE THREAD

**Issue by gogones** [kubb-labs/kubb#1349]
### What version of `kubb` is running?

2.28.2

### What platform is your computer?

MacOs

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"dependencies": {     "@kubb/cli": "^2.28.2",     "@kubb/core": "^2.28.2",     "@kubb/plugin-oas": "^2.28.2",     "@kubb/react": "^2.28.2",     "@kubb/swagger-faker": "^2.28.2",     "@kubb/swagger-msw": "^2.28.2",     "@kubb/swagger-tanstack-query": "^2.28.2",     "@kubb/swagger-ts": "^2.28.2",     "@tanstack/react-query": "^5.59.15",     "axios": "^1.6.7",     "lucide-react": "^0.344.0",     "react": "^18.3.1",     "react-dom": "^18.3.1",     "react-router-dom": "^6.22.3",     "unplugin-kubb": "^0.1.91"   },   "devDependencies": {     "@eslint/js": "^9.9.1",     "@playwright/test": "^1.48.0",     "@testing-library/dom": "^10.4.0",     "@testing-library/jest-dom": "^6.5.0",     "@testing-library/react": "^16.0.1",     "@testing-library/user-event": "^14.5.2",     "@types/node": "^22.7.5",     "@types/react": "^18.3.5",     "@types/react-dom": "^18.3.0",     "@vitejs/plugin-react": "^4.3.1",     "ajv": "^8.17.1",     "autoprefixer": "^10.4.18",     "eslint": "^9.9.1",     "eslint-plugin-react-hooks": "^5.1.0-rc.0",     "eslint-plugin-react-refresh": "^0.4.11",     "globals": "^15.9.0",     "jsdom": "^25.0.1",     "msw": "^2.4.11",     "postcss": "^8.4.35",     "tailwindcss": "^3.4.1",     "typescript": "^5.5.3",     "typescript-eslint": "^8.3.0",     "vite": "^5.4.2",     "vitest": "^2.1.2"   },

### What steps can reproduce the bug?

I want to create a QueryImports template, and I need QueryImports.templates, but it seems that QueryImports hasn't been exported yet, so I can't use it.

### How often does this bug happen?

None

**Comment by stijnvanhulle** [comment]
@gogones in v3 of Kubb, there will be a possibility to override the `importpath`: https://v3.kubb.dev/plugins/plugin-react-query/#query-importpath. This means you don't need to override/define a template. Also with v3, templates will be removed in favour of using generators(almost the same but easier).
