### ISSUE TITLE
pageParam in infiniteQueryOptions queryFn leads to TS6133 error when noUnusedParameters is set

### ISSUE THREAD

**Issue by maxhollmann** [kubb-labs/kubb#1356]
### What version of `kubb` is running?

2.28.3

### What platform is your computer?

Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

@tanstack-query, React

### What steps can reproduce the bug?

* Configure kubb with pluginTanstackQuery to generate infinite query hooks
* Generate some hooks from an openapi.json where [infiniteOverrideParams](https://github.com/kubb-labs/kubb/blob/e8c2a7f3ef6c41e74acaa6ba6bf7b78a9de00769/packages/plugin-react-query/src/components/InfiniteQueryOptions.tsx#L94) will be `false`
* Set `compilerOptions.noUnusedParameters` to `true` in `tsconfig.json`
* Run `tsc`

### How often does this bug happen?

None

### What is the expected behavior?

Kubb should generate the `xInfiniteQueryOptions` function without `pageParams` in the `queryFn`, e.g.:

```typescript
    return infiniteQueryOptions({
        queryKey,
        queryFn: async () => {
```

instead of

```typescript
    return infiniteQueryOptions({
        queryKey,
        queryFn: async ({ pageParam }) => {
```

Since `pageParam` isn't used in the function in this case.

**Comment by stijnvanhulle** [comment]
@maxhollmann This has been resolved as part of the latest v3 beta(`3.0.0-beta.10`)
