### ISSUE TITLE
group.name doesn't call the custom function and always generates the default name

### ISSUE THREAD

**Issue by grreeenn** [kubb-labs/kubb#1376]
### What version of `kubb` is running?

2.28.3

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

-> add the group example from docs to your kubb config (tried with `ts` and `zod`)
```javascript
group: {
  type: 'tag',
  name({ group }){
    return `${group}MyCustomStuff`
  }
}
```
 -> generate -> observe that the folders are named with the default `${group}Controller`

### How often does this bug happen?

None

### What is the expected behavior?

for the example from [docs](https://kubb.dev/plugins/plugin-ts/#group) to work

### Swagger/OpenAPI file?

OpenAPI 3.1

### Additional information

Sorry, in a rush now so didn't dig into the source - but feel free to ping if you need any help with it (you'd probably fix it in 1,5 secs haha)

**Comment by stijnvanhulle** [comment]
@grreeenn It seems that you are using Kubb v3 logic inside a version 2 config. Best to check https://v2.kubb.dev/ when using v`2.x.x`.

V2: https://v2.kubb.dev/plugins/swagger-client/#group-output 
V3: https://www.kubb.dev/plugins/plugin-client/#group-name

**Comment by grreeenn** [comment]
You're totally correct, I've missed the moment when the default docs page switched. Congats on the major version! 👑
