### ISSUE TITLE
Invalid code produced with no swagger ooperationID

### ISSUE THREAD

**Issue by haswalt** [kubb-labs/kubb#1377]
### What version of `kubb` is running?

3.0.1

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"@tanstack/react-query": "^5.59.16",    "@kubb/cli": "^3.0.1", 		"@kubb/core": "^3.0.1", 		"@kubb/plugin-oas": "^3.0.1", 		"@kubb/plugin-react-query": "^3.0.1", 		"@kubb/plugin-redoc": "^3.0.1", 		"@kubb/plugin-ts": "^3.0.1",

### What steps can reproduce the bug?

When generating react-query hooks from a swagger JSON document which doesn't have operationIDs AND has components with multiple `/` (e.g. `/pet/findByStatus`) specified the generated methods are incorrectly named with ` - ` resulting in broken code.

Reproduction: https://codesandbox.io/p/devbox/recursing-matan-9s7vy9?workspaceId=87ae103e-a382-41e4-9760-707f651d23fa

2 observations which can be seen in the reproduction:

1. Without an `operationId` the constructed function name join method and path with `_`
2. Subsequent url path parts are joined using ` - `
3. With invalid method name, the arguments and types are badly formatted, missing `:` between inputs and their types.

In the reproduction there are 3 parts to look at:

1. A generated query using and `operationId` looks like the expected:

```
 /**
 * @description delete a pet
 * @summary Deletes a pet
 * @link /pet/:petId
 */
async function deletePet(petId: DeletePetPathParams["petId"], headers?: DeletePetHeaderParams, config: Partial<RequestConfig> = {}) {
    const res = await client<DeletePetMutationResponse, DeletePet400, unknown>({ method: "DELETE", url: `/pet/${petId}`, headers: { ...headers, ...config.headers }, ...config });
    return res.data;
}
```

2. A generated query WITHOUT an `operationId` but only a single path part looks close to expected BUT the use of `_` doesn't look right:

```
 /**
 * @description Add a new pet to the store
 * @summary Add a new pet to the store
 * @link /pet
 */
async function post_pet(data: PostPetMutationRequest, config: Partial<RequestConfig<PostPetMutationRequest>> = {}) {
    const res = await client<PostPetMutationResponse, PostPet405, PostPetMutationRequest>({ method: "POST", url: `/pet`, data, ...config });
    return res.data;
}
```

3. Without `operationId` and with mutliple path parts the query is completely broken:

```
 /**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * @link /pet/findByStatus
 */
async function get_pet() { }
-findbystatus(params ?  : GetPetFindbystatusQueryParams, config, Partial<RequestConfig> = {});
{
    const res = await client<GetPetFindbystatusQueryResponse, GetPetFindbystatus400, unknown>({ method: "GET", url: `/pet/findByStatus`, params, ...config });
    return res.data;
}
```

This has only started happening as of `3.0.0`

### How often does this bug happen?

Every time

### What is the expected behavior?

Generated methods are valid js/ts

### Swagger/OpenAPI file?

Included in reproduction

**Comment by stijnvanhulle** [comment]
@haswalt An easy fix right now would be to also add `pluginClient` to the Kubb plugins. This one has been added as part of the ReactQuery plugin but is not failing when you are not adding the plugin.(and falling back on the operationId itself) 

I will open a pull request to remove the dependency on `pluginClient`.
