### ISSUE TITLE
PluginTS - deprecated field

### ISSUE THREAD

**Issue by Ericlm** [kubb-labs/kubb#1386]
### What version of `kubb` is running?

3.0.2

### What platform is your computer?

macOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"dependencies": { 		"@kubb/cli": "^3.0.2", 		"@kubb/core": "^3.0.2", 		"@kubb/plugin-oas": "^3.0.2", 		"@kubb/plugin-ts": "^3.0.2" 	}

### What steps can reproduce the bug?

https://codesandbox.io/p/sandbox/quirky-mountain-zdlsdz

In the provided example, the field `id` in the `Order` schema is deprecated in the `petStore.yaml` file, but is not reported as `@deprecated` in the generated types.

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
@Ericlm This has been fixed with Kubb v`3.0.3`

**Comment by Ericlm** [comment]
Thank you very much ! I recently tried kubb for a Vue project, and it could replace a lot of boilerplate work, so thank you for kubb ! 😊
