### ISSUE TITLE
Bug: UUID Generation Uses `z.coercion` Instead of `z.coerce`

### ISSUE THREAD

**Issue by Rikard-Johansson97** [kubb-labs/kubb#1389]
### What version of `kubb` is running?

v3.0.3

### What platform is your computer?

windows

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

react

### Bug: UUID Generation Uses `z.coercion` Instead of `z.coerce`

**Description:**
After the latest update, there is a bug in UUID generation where `z.coercion` is used instead of the correct `z.coerce` method in `zod`. Since `z.coercion` doesn’t exist, this results in runtime errors when parsing UUIDs.

**Steps to Reproduce:**
1. Generate a UUID type with the current setup.
2. Notice that the generated code incorrectly uses `z.coercion`, causing an error.

**Location of the Issue:**
The bug can be found in the following file:  
[plugin-zod/src/parser/index.ts, Line 89](https://github.com/kubb-labs/kubb/blob/2e9bbf717cafb13ab959550e6267af665bd59591/packages/plugin-zod/src/parser/index.ts#L89)

**Suggested Fix:**
Replace `z.coercion` with `z.coerce` in the UUID generation logic. 

### How often does this bug happen?

Every time

### What is the expected behavior?

UUID generation should use `z.coerce` rather than `z.coercion` to align with `zod`'s current API.

**Comment by aburgel** [comment]
FYI, this affects more than just the uuid type.
