### ISSUE TITLE
Zod creates default for nullable property

### ISSUE THREAD

**Issue by Thijmen** [kubb-labs/kubb#1409]
### What version of `kubb` is running?

3.0.6

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

Given following model:

```json
"UpdateStackCommandCommand": {
        "required": [
          "stackId"
        ],
        "type": "object",
        "properties": {
          "stackId": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "default": null,
            "nullable": true
          },
          "description": {
            "type": "string",
            "default": null,
            "nullable": true
          },
          "gitSettings": {
            "$ref": "#/components/schemas/GitSettings"
          }
        }
      },
```

Produces following zod schema:

```ts

 export const updateStackCommandCommandSchema = z.object({ "stackId": z.string().uuid(), "name": z.string().default().nullable().nullish(), "description": z.string().default().nullable().nullish(), "gitSettings": z.lazy(() => gitSettingsSchema).optional() });
 ```

Name and description now get the `default()` method too. I believe this is not intended, as it's nullable where the default is null;
`"description": z.string().default().nullable().nullish(),`

This leads to the following typescript error:
```
Expected 1 arguments, but got 0.ts(2554)
types.d.ts(85, 13): An argument for 'def' was not provided.
```

### How often does this bug happen?

Every time

### What is the expected behavior?

`default()` is not present, because the default is null and the property is nullable.

**Comment by Thijmen** [comment]
I am more than happy to open a PR for this, let me know if this is appreciated.

**Comment by stijnvanhulle** [comment]
@Thijmen Feel free to open a pr, this is more than appreciated. 
Probably another check will be needed here: https://github.com/kubb-labs/kubb/blob/main/packages/plugin-oas/src/SchemaGenerator.ts#L399 to not add `default` to our custom AST.

How it works:

- `SchemaGenerator` goes over the the openAPI/Swagger file(plugin-oas)
- SchemaGenerator` creates a custom AST(array of objects with `type` and some extra meta data.
- TypeScript, Zod and faker uses this generated AST to parse the data(see parser/index.ts)
- Types, faker functions and Zod schemas are being created and save to a file

**Comment by Thijmen** [comment]
@stijnvanhulle I'll do my best! How can I run the tests locally at best?

**Comment by stijnvanhulle** [comment]
@Thijmen A new version of Kubb has been release with your change: 3.0.9
