### ISSUE TITLE
Issue with `data` propagation in generated functions by `@kubb/plugin-faker`

### ISSUE THREAD

**Issue by wmahad** [kubb-labs/kubb#1411]
### What version of `kubb` is running?

3.0.6

### What steps can reproduce the bug?

There seems to be an issue with the way some functions generated by `@kubb/plugin-faker` handle the `data` parameter, leading to `data` not being propagated as intended. Here's an example of the problematic code:

```typescript
export function createPartnersListQueryResponse(data?: Partial<PartnersListQueryResponse>) {
  faker.seed(2);
  return faker.helpers.arrayElement<any>([createPartnersList200()]) || data;
}
```

### Issue
In the line:

```typescript
return faker.helpers.arrayElement<any>([createPartnersList200()]) || data;
```

The `||` operator ensures that `data` will **never** be executed, as `faker.helpers.arrayElement<any>([createPartnersList200()])` always returns a value. This means the `data` parameter passed to `createPartnersListQueryResponse` is effectively ignored, and there’s no way to propagate it down to `createPartnersList200` or `createPaginatedOrganizationOutputList`.

### Suggested Solution
The `data` parameter should be passed down the chain to ensure it is used when generating the final response. Here's a potential fix for the `createPartnersListQueryResponse` function:

```typescript
export function createPartnersListQueryResponse(data?: Partial<PartnersListQueryResponse>) {
  faker.seed(2);
  return faker.helpers.arrayElement<any>([createPartnersList200(data)]);
}
```

This ensures that `data` is passed to `createPartnersList200`, which could then propagate it further down to `createPaginatedOrganizationOutputList` as follows:

```typescript
export function createPartnersList200(data?: Partial<PartnersListQueryResponse>) {
  faker.seed(2);
  return createPaginatedOrganizationOutputList(data);
}

export function createPaginatedOrganizationOutputList(
  data?: Partial<PaginatedOrganizationOutputList>
) {
  faker.seed(2);
  return {
    ...{
      results: faker.helpers.multiple(() => createOrganizationOutput()) as any,
      _meta: {
        pagination: {
          page: faker.number.int(),
          pages: faker.number.int(),
          count: faker.number.int(),
          page_size: faker.number.int(),
        },
      },
      _links: {
        first: faker.internet.url(),
        last: faker.internet.url(),
        next: faker.internet.url(),
        prev: faker.internet.url(),
      },
    },
    ...(data || {}), // Data is finally merged here
  };
}
```

### Expected Behavior
By passing `data` through the chain of functions (`createPartnersListQueryResponse` → `createPartnersList200` → `createPaginatedOrganizationOutputList`), users should be able to customize the output by overriding specific fields.

### Steps to Reproduce
1. Clone the example [StackBlitz project](https://stackblitz.com/edit/vitejs-vite-hptzg2).
2. Run the command `npm run generate` to generate the code.
3. Call `createPartnersListQueryResponse` with a `data` parameter.
4. Observe that the `data` parameter is not applied to the output.

### Additional Suggestion
It would be helpful if the `@kubb/plugin-oas` plugin provided an option **not to store the generated output** (e.g., skipping or discarding the generated files). This would allow users to use the plugin purely for runtime generation without persisting files to the file system.

**Comment by stijnvanhulle** [comment]
@wmahad Thanks for open this issue, there is indeed a mismatch. A pr will be opened soon that will change the order of data(always first). This will already resolve a big part of your issue.

To chain down the `data` object is quite hard to do, Kubb is not aware of the tree structure of the different schemas. In your example the first `data` object(`createPartnersList200`) has type `PartnersListQueryResponse` but then in `createPaginatedOrganizationOutputList` it is a totally different type(`PaginatedOrganizationOutputList`).

How could Kubb be aware of this change and also how could we transform when chaining down? Not sure if that is possible based on the Swagger/OpenAPI file.

**Comment by stijnvanhulle** [comment]
@wmahad Version `3.0.10` will already resolve the order of the data object.

**Comment by wmahad** [comment]
@stijnvanhulle  Thanks for the update and for addressing this! The new version `3.0.10` is perfect, especially since it ensures that `data` is always first—this will indeed solve a large part of the issue. 

As for chaining down the `data` object, I understand the complexity, given that Kubb doesn’t have inherent awareness of the schema tree structure. It makes sense that transforming between types like `PartnersListQueryResponse` and `PaginatedOrganizationOutputList` is challenging without additional metadata in the Swagger/OpenAPI file. Thanks for clarifying that.

On a related note, I have a proposal that might be more relevant to a different plugin, `@kubb/plugin-msw`. It would be great if we could provide either a `data` object or a function as a parameter for handlers. Here's an example of what I mean:

```typescript
export function apiKeysUpdateHandler(data?: ApiKeysUpdateMutationResponse | Function, options = {}) {
  return http.put('*/api/v2/api-keys/:uuid/', function handler(info) {
    if (isFunction(data)) return data(info);

    return new Response(
      JSON.stringify(createApiKeysUpdateMutationResponse(data)),
      {
        headers: {
          'Content-Type': 'application/json',
        },
        ...options,
      }
    );
  });
}
```

This would allow users to customize the handler, for example:

```typescript
apiKeysUpdateHandler(({ params }) => {
  if (params.someKey) {
    return new Response(
      JSON.stringify({ error: 'some error response' }),
      { status: 400 }
    );
  }
  return new Response(
    JSON.stringify({ newData: 'new data' }),
    { status: 200 }
  );
});
```

This flexibility would make testing and mocking much easier, especially in scenarios where the response needs to change dynamically. What do you think? Could this be a worthwhile addition to `@kubb/plugin-msw`?

**Comment by stijnvanhulle** [comment]
@wmahad Sure, this looks like great idea. could you open another issue with what you are explaining here?
There we could start a discussing to see what other developers would need.
