### ISSUE TITLE
Applying required on fields inherited using allOf are not generated as required

### ISSUE THREAD

**Issue by ksilverhav** [kubb-labs/kubb#1433]
### What version of `kubb` is running?

3.0.13

### What kind of platform do you use?

MacOS

### How does your `kubb.config.ts` config look like

```typescript
import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginTs } from '@kubb/plugin-ts';
import { pluginZod } from '@kubb/plugin-zod';

export default defineConfig({
  input: {
    path: './src/openapi/test.yaml',
  },
  output: {
    path: './src/generated',
  },
  plugins: [
    pluginOas(),
    pluginTs({
      output: {
        path: './types',
      },
    }),
    pluginZod({
      output: {
        path: './zod',
      },
    }),
  ],
});
```

### Swagger/OpenAPI file?

```bash
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
  /address:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
  /full-address:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FullAddress"
components:
  schemas:
    Address:
      type: object
      properties:
        countryCode:
          type: string
        postalCode:
          type: string
        city:
          type: string
        streetName:
          type: string
        streetNumber:
          type: string
      required:
        - countryCode
        - postalCode
        - city
    FullAddress:
      allOf:
        - $ref: "#/components/schemas/Address"
      required:
        - streetName
        - streetNumber
```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON
"@kubb/cli": "^3.0.13",
"@kubb/core": "^3.0.13",
"@kubb/plugin-oas": "^3.0.13",
"@kubb/plugin-ts": "^3.0.13",
"@kubb/plugin-zod": "^3.0.13",
```

### What steps can reproduce the bug?

https://stackblitz.com/edit/stackblitz-starters-bqeaft
Running `npm run generate` in the stackblitz generates the oas, typescript and zod types, which can be found under `src/generated`.

### How often does this bug happen?

Every time

### What is the expected behavior?

`FullAddress` in `src/generated/types/FullAddress.ts` and `fullAddressSchema` in `src/generated/zod/fullAddressSchema.ts` should have all fields required, but the only fields required are the ones which are required in `Address`. 

### Additional information

Using the plugin `"@kubb/plugin-redoc": "^3.0.13"` and viewing the generated html file, all fields are correctly shown as required for the path `/full-address`. I didn't include this in the stackblitz above since it's working as intended.

**Comment by stijnvanhulle** [comment]
@ksilverhav v`3.0.14` will resolve this issue. This will not be perfect for Zod(the infer will not completely Infer the required fields) but the parse will fail.

**Comment by ksilverhav** [comment]
@stijnvanhulle Hi, this issue has re-occurred, I've tested this with v3.4.5 and FullAddress is defined as it was when this bug was reported: `export type FullAddress = Address`
Required fields are not taken into consideration. This seems to occur when FullAddress (in this case) doesn't have it's own properties, only sets required on the inherited properties.

Shall this issue be re-opened or should I report a new issue?

**Comment by ksilverhav** [comment]
Reported a new bug for this https://github.com/kubb-labs/kubb/issues/1522
