### ISSUE TITLE
pluginTs: add property 'type' for the kind of output

### ISSUE THREAD

**Issue by nimo23** [kubb-labs/kubb#1450]
### What is the problem this feature would solve?

Please add the property 'type'  (or similar) for the output:

```
pluginTs({
    type: 'interface' // will generate interfaces instead of types
    ...
})
```

`type: 'type' | 'interface'`

- use `type` to use Typescript types (default)
- use `interface` to use Typescript interfaces

**Comment by stijnvanhulle** [comment]
v 3.3.0 of Kubb now has the option to define the syntax being used. For that you could use `syntaxtype` https://www.kubb.dev/plugins/plugin-ts/#syntaxtype. Thanks for your proposal, feel free to reach out when it does not work as indended.


For example:

```
 pluginTs({
      output: {
        path: 'models.ts',
        barrelType: false,
      },
      enumType: 'enum',
      syntaxType: 'interface',
    })
```
