### ISSUE TITLE
pluginZod: format generated code

### ISSUE THREAD

**Issue by nimo23** [kubb-labs/kubb#1453]
### What is the problem this feature would solve?

Currently, the generated `z.object` is written in one line. Please format the generated `z.object` to make it more readable by formatting it as follows:

```
// each prop will be in a new line
 export const userSchema = z.object({ 
    "id": z.string().optional(), 
    "username": z.string().regex(new RegExp("\S")).min(2).max(20).describe("The username"), 
    "email": z.string().describe("The email"),
..
})
```

By the way, other files generated by Kubb are also preformatted to make them more readable. It would be nice to preformat Zod files as well.

**Comment by stijnvanhulle** [comment]
@nimo23 v3.3.0 will introduce a better internal formatter that will resolve your issue :)
