### ISSUE TITLE
pluginZod: use Regular expression literal instead of RegExp-contructor

### ISSUE THREAD

**Issue by nimo23** [kubb-labs/kubb#1454]
### What is the problem this feature would solve?

kubb generates a regex by using RegExp()-constructor:

```
// uses RegExp-contructor
"username": z.string().regex(new RegExp("\\S")).min(2).max(20)
```

Please consider to use `Regular expression literal` instead of `RegExp-contructor`:

```
// uses Regular expression literal
"username": z.string().regex(/\S/).min(2).max(20)
```

According to SonarLint, Regular expression literal:

- it's shorter
- more readable
- do not need to be escaped
- and can also be more performant because Regular expression literal are compiled only once when the script is loaded

**Comment by stijnvanhulle** [comment]
@nimo23 This change will be part of kubb v3.3.0
