### ISSUE TITLE
Schema with a string type and a const generate a regular string instead of the const

### ISSUE THREAD

**Issue by Rmvandiepen** [kubb-labs/kubb#1477]
### What version of `kubb` is running?

3.3.4

### What kind of platform do you use?

MacOS

### How does your `kubb.config.ts` config look like

```typescript
export default defineConfig({
  root: '.',
  input: {
    path: './temp_schema.yml',
  },
  output: {
    path: './src/@generated',
    clean: true,
  },
  plugins: [
    pluginOas({ validate: false }),
    pluginTs({
      output: {
        path: 'InternalApiTypes.ts',
        barrelType: 'all',
      },
      enumType: 'enum',
      enumSuffix: '',
    }),
  ],
});
```

### Swagger/OpenAPI file?

```bash
get:
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          oneOf:
          - type: integer
          - type: string
            const: inf
```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON
-
```

### What steps can reproduce the bug?

When trying to generate the internal types from the open api schema, the results of a schema type string with a `const (inf)` does generate the interface with `string`. Based on the schema above (using oneOf) it generates:
```
page_size?: number | string;
```

### How often does this bug happen?

Every time

### What is the expected behavior?

Instead I'd expect the typing to be:
```
page_size?: number | "inf";
```

**Comment by stijnvanhulle** [comment]
@Rmvandiepen Be aware that `const` is only part of openAPI v3, if your file does not have that set then it will be ignored and fallback on the type(string here).
