### ISSUE TITLE
Make Kubb work with external `refs`

### ISSUE THREAD

**Issue by stijnvanhulle** [kubb-labs/kubb#865]
### Discussed in https://github.com/kubb-project/kubb/discussions/859

<div type='discussions-op-text'>

<sup>Originally posted by **popuguytheparrot** March 11, 2024</sup>
Hi there. I'm getting an error when trying to generate types from a schema, where the paths and responses use $ref in files with their declarations for reuse. What am I doing wrong?

![image](https://github.com/kubb-project/kubb/assets/19804652/0b8ad2be-e516-42ad-805a-e9b6c3ba3d71)
![image](https://github.com/kubb-project/kubb/assets/19804652/c852970e-1531-45f1-ac9d-47177b5b02cb)
<img width="282" alt="Снимок экрана 2024-03-11 в 19 14 14" src="https://github.com/kubb-project/kubb/assets/19804652/b9ed2227-f939-44d3-9345-9a7c002d84a2">
</div>

**Comment by kopach** [comment]
take a look on https://www.npmjs.com/package/json-refs - works great for me. I run this before kubb
