### ISSUE TITLE
Hooks.done are not run when using unplugin-kubb.

### ISSUE THREAD

**Issue by FluidSense** [kubb-labs/kubb#942]
### What version of `kubb` is running?

kubb/2.13.0 darwin-x64 node-v21.5.0

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

 "swr": "^2.2.5",     "unplugin-kubb": "^0.1.31",     "zod": "^3.22.4",    "prettier": "^3.2.5",  "react": "^18.2.0",     "react-dom": "^18.2.0", "vite":"^5.1.5"

### What steps can reproduce the bug?

Hooks.done never seems to be invoked by unplugin-kubb. The exact example in https://kubb.dev/config/hooks#hooks-done, but prettier is never invoked.

 - Make a new repository
 - Find an OpenAPI-definition
 - Add done hooks to config like in example
 - Add unplugin-kubb to Vite
 - Run Vite
 - See generated files, but not formatted

It works as intended if kubb is invoked by CLI.

### How often does this bug happen?

Every time

### What is the expected behavior?

Formatted files through Prettier after generation.

### Swagger/OpenAPI file?

Internal only, sadly. Hopefully N/A.

**Comment by stijnvanhulle** [comment]
@FluidSense Not sure if we want to do this. Running tasks outside Vite or Webpack could result in a loop(when Vite/Webpack uses the watcher) or could slow down Vite/Webpack. 
We should keep that plugin clean and when you want something like post hooks => use Kubb CLI.

**Comment by FluidSense** [comment]
@stijnvanhulle I see! Then it would be nice to have that added to the docs. That hooks are only ran in CLI. Maybe it could also be grouped under some config-option named `cli` or something? Else, I would expect the plugin to use the config just as the CLI does.
