### ISSUE TITLE
Add the ability to import query hooks from a custom path

### ISSUE THREAD

**Issue by Treycos** [kubb-labs/kubb#956]
### What is the problem this feature would solve?

Projects may have custom override hooks that wrap around the standard `useQuery`,` useMutation` and `useInfiniteQuery`.

These hooks usually have the same signature, names and overall behavior of the RQ ones.
They may implement additional logic do the vanilla hook that would be inefficient to generate dynamically.

Right now, implementing them requires recreating all `Query` templates, which can be overwhelming considering the change is only an import path

### What is the feature you are proposing to solve the problem?

One solution is to add a `string` parameter in the config option

This new param would only change the import path from @tanstack/react-query to what is supplied.

This param could be supplied for any rendering framework and replace the import paths given here:
https://github.com/kubb-labs/kubb/blob/main/packages/swagger-tanstack-query/src/utils.ts

Another solution would be to add the import template as a customizable component: 

```
      templates: {
        mutation: Mutation.templates,
        query: Query.templates,
        queryOptions: QueryOptions.templates,
        queryKey: QueryKey.templates,
        operations: Operations.templates,
        imports: Imports.templates
        ...templates,
      },
```
This template would allow user to edit the default import without having to edit other templates

**Comment by stijnvanhulle** [comment]
`imports` has been added to the templates and another option has been added to override the import without using React/templates.

The following config will use `import { useQuery } form '@kubb/react-query'` instead of using `import { useQuery } form '@tanstack/react-query`. 

> Important note: This will work so long you are using the same syntax of UseQuery.

```
import { defineConfig } from '@kubb/core'
import { definePlugin as createSwagger } from '@kubb/swagger'
import { definePlugin as createSwaggerTanstackQuery } from '@kubb/swagger-tanstack-query'
import { definePlugin as createSwaggerTS } from '@kubb/swagger-ts'

export default defineConfig({
  input: {
    path: './petStore.yaml',
  },
  output: {
    path: './src/gen',
  },
  plugins: [
    createSwagger({ output: false }),
    createSwaggerTS({}),
    createSwaggerTanstackQuery({
      query: {
        importPath: "@kubb/react-query"
      },
    }),
  ],
})
```

See https://kubb.dev/plugins/swagger-tanstack-query/#query-importpath and https://kubb.dev/examples/advanced for an example of how to configure this.
