### ISSUE TITLE
Support MSW response override

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [kubb-labs/kubb#961]
### What is the problem this feature would solve?

add support
* to provide response faker overrides in MSW generated code
* to mock error responses

### What is the feature you are proposing to solve the problem?

Faker already supports an option to specify overrides
Would be cool if it would be possible to provide overrides in MSW code as well

```ts
import { http, HttpResponse } from 'msw';

export const requestHandler = (data: Parameters<typeof createMutationResponse>) => http.put(
  '*/...',
  function handler(info) {
    return HttpResponse.json(
      createMutationResponse(data),
      {
        status: 200,
      },
    );
  },
);
```

Also I didn't see how to mock error responses with kubb library
e.g. 404 and 400

**Comment by stijnvanhulle** [comment]
For this, you can use the templates and create your own function that will pass through data. I can provide you with an example of how you can achieve this but right now we are not planning to add this as the default to Kubb.

Something we can change in v3 of Kubb if more people wants this as the default.
