### ISSUE TITLE
Nullable fields are always required in TS

### ISSUE THREAD

**Issue by g-gagnon** [kubb-labs/kubb#969]
### What version of `kubb` is running?

kubb/2.12.3 darwin-arm64 node-v20.10.0

### What steps can reproduce the bug?

When a field is marked as nullable, but it not in the `required` array, the generated property is not optional.

### How often does this bug happen?

Every time

### What is the expected behavior?

A nullable and optional field should result in `foo?: string | null`.

### Additional information

The feature seems to have been implemented correctly initially, based off [the tests](https://github.com/kubb-labs/kubb/pull/493/files#diff-24b6f73c2dff90f014faaf322b56c080adba0d4f9ec63f1de8ffa918b895a518R107-R124)

We can see that `foo?: string | null` is the expected result of an optional and nullable field. 
In the current test suite, we can see that for a [similar scenario](https://github.com/kubb-labs/kubb/blob/main/packages/swagger-ts/src/SchemaGenerator.test.tsx#L106), the [expected schema](https://github.com/kubb-labs/kubb/blob/main/packages/swagger-ts/src/__snapshots__/SchemaGenerator.test.tsx.snap#L430) is missing the optional property.

**Comment by stijnvanhulle** [comment]
@g-gagnon A extra check was missing to add the questionMark to the type, the following pr will resolve this: https://github.com/kubb-labs/kubb/pull/970.
