### ISSUE TITLE
[Swagger-Faker]: Add dateString for dateType 

### ISSUE THREAD

**Issue by rwhendry** [kubb-labs/kubb#979]
### What is the problem this feature would solve?

Currently, there are only 2 choices for `dateType` properties in **swagger-faker** and there are no options for dateString. I want this feature to generate any random date but in string type. For example it can generate `2024-05-03`.

### What is the feature you are proposing to solve the problem?

Add `dateString` for `dateType` property in **swagger-faker**. The implementation might be something like this
`faker.date.anytime().toString()`

### What alternatives have you considered?

Other alternatives is just to replace the **string** type in `dateType` as it generates random string that isn't in date type for a date field (and will break if used together with **swagger-zod**)

**Comment by stijnvanhulle** [comment]
@rwhendry I will go for the alternative where `faker.string.alpha()` will be replaced with `faker.date.anytime().toString()` when using `dateType: 'string'`
