### ISSUE TITLE
Kubb loses the path to the files if $ref is used

### ISSUE THREAD

**Issue by aaronb-reach** [kubb-labs/kubb#990]
### What version of `kubb` is running?

kubb/2.18.1 linux-x64 node-v20.11.0

### What platform is your computer?

Linux/MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```
{
  "name": "kubb",
  "version": "1.0.0",
  "scripts": {
    "generate": "kubb generate --config kubb.config.js"
  },
  "devDependencies": {
    "@kubb/cli": "^2.18.1",
    "@kubb/core": "^2.18.1",
    "@kubb/swagger": "^2.18.1",
    "@kubb/swagger-ts": "^2.18.1",
    "@kubb/swagger-zod": "^2.18.1"
  }
}
```

### What steps can reproduce the bug?

When trying to generate types for yml docs that include a `$ref` to a relative path, the file at the relative path is not found

![Screenshot 2024-05-09 at 12 14 01](https://github.com/kubb-labs/kubb/assets/157378327/57524da8-7b77-4b00-affd-31c6c9a9d5ff)

This seems similar to https://github.com/kubb-labs/kubb/discussions/859 which states `v2.14.0` fixed this, but i am still seeing this with `v2.18.1`. Am i missing something?

Many thanks!

Reproduction of issue: https://github.com/burt202/kubb-test
Line where `$ref` is used: https://github.com/burt202/kubb-test/blob/master/docs/main.yml#L30

To recreate:

- clone repo above
- npm ci
- npm run generate

### How often does this bug happen?

Every time

### What is the expected behavior?

It should import from path of input not path of kubb config

### Swagger/OpenAPI file?

Included in linked test repo

**Comment by stijnvanhulle** [comment]
@aaronb-reach Replaced the bundle logic by the one of @redocly/openapi-core and that one seems to do the trick. v2.18.2 will resolve your issue :)

**Comment by aaronb-reach** [comment]
Wow that was quick! Much appreciated!
